In [1]:
import pandas as pd
import numpy as np 
import re

In [2]:
nacoesunidas = pd.read_csv(r'C:\Users\carlo\OneDrive\ANALYTICS\ANALYTICS - IRONHACK\PORTFOLIO\PROJETOS\PROJETO_FINAL_CURSO\Nacoes_Unidas\Dados_Nacoes_Unidas\IAEG+DF_UNDATA_MDG+1.2_2023_05_15_18_02_14.csv', 
                        sep=';',
                        low_memory=False)

In [3]:
nacoesunidas.head()

,DATAFLOW,FREQ,SERIES,UNIT,LOCATION,AGE_GROUP,SEX,REF_AREA,SOURCE_TYPE,TIME_PERIOD,OBS_VALUE,UNIT_MULT,TIME_DETAIL,NATURE,SOURCE_DETAIL,FOOTNOTES
0,IAEG:DF_UNDATA_MDG(1.2),A,AG_LND_FRST,PERCENT,T,NaN,NaN,ABW,NaN,1990,0.000000,0,1990,E,NaN,NaN
1,IAEG:DF_UNDATA_MDG(1.2),A,AG_LND_FRST,PERCENT,T,NaN,NaN,ABW,NaN,2000,0.000000,0,2000,E,NaN,NaN
2,IAEG:DF_UNDATA_MDG(1.2),A,AG_LND_FRST,PERCENT,T,NaN,NaN,ABW,NaN,2005,0.000000,0,2005,E,NaN,NaN
3,IAEG:DF_UNDATA_MDG(1.2),A,AG_LND_FRST,PERCENT,T,NaN,NaN,ABW,NaN,2010,0.000000,0,2010,E,NaN,NaN
4,IAEG:DF_UNDATA_MDG(1.2),A,AG_LND_FRST,PERCENT,T,NaN,NaN,AFG,NaN,1990,2.070266,0,1990,E,NaN,NaN

In [4]:
nacoesunidas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 387044 entries, 0 to 387043
Data columns (total 16 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   DATAFLOW       387044 non-null  object
 1   FREQ           387044 non-null  object
 2   SERIES         387044 non-null  object
 3   UNIT           387044 non-null  object
 4   LOCATION       387044 non-null  object
 5   AGE_GROUP      304147 non-null  object
 6   SEX            302994 non-null  object
 7   REF_AREA       387044 non-null  object
 8   SOURCE_TYPE    0 non-null       float64
 9   TIME_PERIOD    387044 non-null  int64
 10  OBS_VALUE      320677 non-null  float64
 11  UNIT_MULT      387044 non-null  int64
 12  TIME_DETAIL    387044 non-null  int64
 13  NATURE         315236 non-null  object
 14  SOURCE_DETAIL  0 non-null       float64
 15  FOOTNOTES      94713 non-null   object
dtypes: float64(3), int64(3), object(10)
memory usage: 47.2+ MB

In [5]:
nacoesunidas['REF_AREA'] = nacoesunidas['REF_AREA'].replace({  'CAN': 'Canada',
  'CPV': 'Cape Verde',
  'CYM': 'Cayman Islands',
  'CAF': 'Central African Republic',
  'TCD': 'Chad',
  '830': 'Channel Islands',
  'CHL': 'Chile',
  'CHN': 'China',
  'HKG': 'Hong Kong Special Administrative Region of China',
  'MAC': 'Macao Special Administrative Region of China',
  'COL': 'Colombia',
  'COM': 'Comoros',
  'COG': 'Congo',
  'COK': 'Cook Islands',
  'CRI': 'Costa Rica',
  'CIV': "CÃ´te d'Ivoire",
  'HRV': 'Croatia',
  'CUB': 'Cuba',
  'CYP': 'Cyprus',
  'CZE': 'Czech Republic',
  'PRK': "Democratic People's Republic of Korea",
  'COD': 'Democratic Republic of the Congo',
  'DNK': 'Denmark',
  'DJI': 'Djibouti',
  'DMA': 'Dominica',
  'DOM': 'Dominican Republic',
  'ECU': 'Ecuador',
  'EGY': 'Egypt',
  'SLV': 'El Salvador',
  'GNQ': 'Equatorial Guinea',
  'ERI': 'Eritrea',
  'EST': 'Estonia',
  'ETH': 'Ethiopia',
  'FRO': 'Faeroe Islands',
  'FLK': 'Falkland Islands (Malvinas)',
  'FJI': 'Fiji',
  'FIN': 'Finland',
  'FRA': 'France',
  'GUF': 'French Guiana',
  'PYF': 'French Polynesia',
  'GAB': 'Gabon',
  'GMB': 'Gambia',
  'GEO': 'Georgia',
  'DEU': 'Germany',
  'GHA': 'Ghana',
  'GIB': 'Gibraltar',
  'GRC': 'Greece',
  'GRL': 'Greenland',
  'GRD': 'Grenada',
  'GLP': 'Guadeloupe',
  'GUM': 'Guam',
  'GTM': 'Guatemala',
  'GIN': 'Guinea',
  'GNB': 'Guinea-Bissau',
  'GUY': 'Guyana',
  'HTI': 'Haiti',
  'HND': 'Honduras',
  'HUN': 'Hungary',
  'ISL': 'Iceland',
  'IND': 'India',
  'IDN': 'Indonesia',
  'IRN': 'Iran (Islamic Republic of)',
  'IRQ': 'Iraq',
  'IRL': 'Ireland',
  'ISR': 'Israel',
  'ITA': 'Italy',
  'JAM': 'Jamaica',
  'AFG': 'Afghanistan',
  'ALB': 'Albania',
  'DZA': 'Algeria',
  'ASM': 'American Samoa',
  'AND': 'Andorra',
  'AGO': 'Angola',
  'AIA': 'Anguilla',
  'ATG': 'Antigua and Barbuda',
  'ARG': 'Argentina',
  'ARM': 'Armenia',
  'ABW': 'Aruba',
  'AUS': 'Australia',
  'AUT': 'Austria',
  'AZE': 'Azerbaijan',
  'BHS': 'Bahamas',
  'BHR': 'Bahrain',
  'BGD': 'Bangladesh',
  'BRB': 'Barbados',
  'BLR': 'Belarus',
  'BEL': 'Belgium',
  'BLZ': 'Belize',
  'BEN': 'Benin',
  'BMU': 'Bermuda',
  'BTN': 'Bhutan',
  'BOL': 'Bolivia (Plurinational State of)',
  'BIH': 'Bosnia and Herzegovina',
  'BWA': 'Botswana',
  'BRA': 'Brazil',
  'VGB': 'British Virgin Islands',
  'BRN': 'Brunei Darussalam',
  'BGR': 'Bulgaria',
  'BFA': 'Burkina Faso',
  'BDI': 'Burundi',
  'KHM': 'Cambodia',
  'CMR': 'Cameroon',
  'JPN': 'Japan',
  'JOR': 'Jordan',
  'KAZ': 'Kazakhstan',
  'KEN': 'Kenya',
  'KIR': 'Kiribati',
  'KWT': 'Kuwait',
  'KGZ': 'Kyrgyzstan',
  'LAO': "Lao People's Democratic Republic",
  'LVA': 'Latvia',
  'LBN': 'Lebanon',
  'LSO': 'Lesotho',
  'LBR': 'Liberia',
  'LBY': 'Libyan Arab Jamahiriya',
  'LIE': 'Liechtenstein',
  'LTU': 'Lithuania',
  'LUX': 'Luxembourg',
  'MDG': 'Madagascar',
  'MWI': 'Malawi',
  'MYS': 'Malaysia',
  'MDV': 'Maldives',
  'MLI': 'Mali',
  'MLT': 'Malta',
  'MHL': 'Marshall Islands',
  'MTQ': 'Martinique',
  'MRT': 'Mauritania',
  'MUS': 'Mauritius',
  'MYT': 'Mayotte',
  'MEX': 'Mexico',
  'FSM': 'Micronesia (Federated States of)',
  'MDA': 'Republic of Moldova',
  'MCO': 'Monaco',
  'MNG': 'Mongolia',
  'MNE': 'Montenegro',
  'MSR': 'Montserrat',
  'MAR': 'Morocco',
  'MOZ': 'Mozambique',
  'MMR': 'Myanmar',
  'NAM': 'Namibia',
  'NRU': 'Nauru',
  'NPL': 'Nepal',
  'NLD': 'Netherlands',
  'ANT': 'Netherlands Antilles',
  'NCL': 'New Caledonia',
  'NZL': 'New Zealand',
  'NIC': 'Nicaragua',
  'NER': 'Niger',
  'NGA': 'Nigeria',
  'NIU': 'Niue',
  'MNP': 'Northern Mariana Islands',
  'NOR': 'Norway',
  'PSE': 'State of Palestine',
  'OMN': 'Oman',
  'PAK': 'Pakistan',
  'PLW': 'Palau',
  'PAN': 'Panama',
  'PNG': 'Papua New Guinea',
  'PRY': 'Paraguay',
  'PER': 'Peru',
  'PHL': 'Philippines',
  'POL': 'Poland',
  'PRT': 'Portugal',
  'PRI': 'Puerto Rico',
  'QAT': 'Qatar',
  'KOR': 'Republic of Korea',
  'REU': 'RÃ©union',
  'ROU': 'Romania',
  'RUS': 'Russian Federation',
  'RWA': 'Rwanda',
  'SHN': 'Saint Helena',
  'KNA': 'Saint Kitts and Nevis',
  'LCA': 'Saint Lucia',
  'SPM': 'Saint Pierre and Miquelon',
  'VCT': 'Saint Vincent and the Grenadines',
  'WSM': 'Samoa',
  'SMR': 'San Marino',
  'STP': 'Sao Tome and Principe',
  'SAU': 'Saudi Arabia',
  'SEN': 'Senegal',
  'SRB': 'Serbia',
  'SYC': 'Seychelles',
  'SLE': 'Sierra Leone',
  'SGP': 'Singapore',
  'SVK': 'Slovakia',
  'SVN': 'Slovenia',
  'SLB': 'Solomon Islands',
  'SOM': 'Somalia',
  'ZAF': 'South Africa',
  'SSD': 'South Sudan',
  'ESP': 'Spain',
  'LKA': 'Sri Lanka',
  'SDN': 'Sudan',
  'SUR': 'Suriname',
  'SWZ': 'Swaziland',
  'SWE': 'Sweden',
  'CHE': 'Switzerland',
  'SYR': 'Syrian Arab Republic',
  'TJK': 'Tajikistan',
  'THA': 'Thailand',
  'MKD': 'The former Yugoslav Republic of Macedonia',
  'TLS': 'Timor-Leste',
  'TGO': 'Togo',
  'TKL': 'Tokelau',
  'TON': 'Tonga',
  'TTO': 'Trinidad and Tobago',
  'TUN': 'Tunisia',
  'TUR': 'Turkey',
  'TKM': 'Turkmenistan',
  'TCA': 'Turks and Caicos Islands',
  'TUV': 'Tuvalu',
  'UGA': 'Uganda',
  'UKR': 'Ukraine',
  'ARE': 'United Arab Emirates',
  'GBR': 'United Kingdom of Great Britain and Northern Ireland',
  'TZA': 'United Republic of Tanzania',
  'USA': 'United States of America',
  'VIR': 'United States Virgin Islands',
  'URY': 'Uruguay',
  'UZB': 'Uzbekistan',
  'VUT': 'Vanuatu',
  'VEN': 'Venezuela (Bolivarian Republic of)',
  'VNM': 'Viet Nam',
  'WLF': 'Wallis and Futuna Islands',
  'ESH': 'Western Sahara',
  'YEM': 'Yemen',
  'ZMB': 'Zambia',
  'ZWE': 'Zimbabwe'})

In [6]:
nacoesunidas.head()

,DATAFLOW,FREQ,SERIES,UNIT,LOCATION,AGE_GROUP,SEX,REF_AREA,SOURCE_TYPE,TIME_PERIOD,OBS_VALUE,UNIT_MULT,TIME_DETAIL,NATURE,SOURCE_DETAIL,FOOTNOTES
0,IAEG:DF_UNDATA_MDG(1.2),A,AG_LND_FRST,PERCENT,T,NaN,NaN,Aruba,NaN,1990,0.000000,0,1990,E,NaN,NaN
1,IAEG:DF_UNDATA_MDG(1.2),A,AG_LND_FRST,PERCENT,T,NaN,NaN,Aruba,NaN,2000,0.000000,0,2000,E,NaN,NaN
2,IAEG:DF_UNDATA_MDG(1.2),A,AG_LND_FRST,PERCENT,T,NaN,NaN,Aruba,NaN,2005,0.000000,0,2005,E,NaN,NaN
3,IAEG:DF_UNDATA_MDG(1.2),A,AG_LND_FRST,PERCENT,T,NaN,NaN,Aruba,NaN,2010,0.000000,0,2010,E,NaN,NaN
4,IAEG:DF_UNDATA_MDG(1.2),A,AG_LND_FRST,PERCENT,T,NaN,NaN,Afghanistan,NaN,1990,2.070266,0,1990,E,NaN,NaN

In [7]:
df_series = "[AG_LND_FRST] - Land area covered by forest[DC_AID_LLDC] - ODA received in landlocked developing countries[DC_AID_LLDCG] - ODA received in landlocked developing countries as a percentage of their GNI[DC_AID_SIDS] - ODA received in small island developing states[DC_AID_SIDSG] - ODA received in small island developing states as a percentage of their GNI[DC_HPC_COMR] - Debt relief committed under HIPC Initiative, cumulative[DC_HPC_MDRI] - Debt relief delivered in full under MDRI initiative, cumulative[DC_HPC_STTS] - Countries that have reached their HIPC decision points and countries that have reached their HIPC completion points (cumulative)[DC_ODA_LDCG] - Net ODA to LDCs as a percentage of OECD/DAC donors' GNI[DC_ODA_LDCS] - Net ODA to LDCs[DC_ODA_SOCL] - ODA to basic social services[DC_ODA_SOCP] - ODA to basic social services as a percentage of sector-allocable ODA[DC_ODA_TCAP] - ODA provided to help build trade capacity[DC_ODA_TOTG] - Net ODA as a percentage of OECD/DAC donors' GNI[DC_ODA_TOTL] - Net ODA[DC_ODA_UNTD] - ODA that is untied[DT_TDS_DECT] - Debt service as percentage of exports of goods and services and net income[EG_USE_COMM] - Energy use[EG_USE_SLFL] - Population using solid fuels[EN_ATM_CFC] - Consumption of ozone-depleting CFCs[EN_ATM_CO2] - Carbon dioxide emissions[EN_ATM_CO2_CDIAC] - Carbon dioxide emissions (CDIAC)[EN_ATM_CO2PC] - Carbon dioxide emissions per capita[EN_ATM_CO2PC_CDIAC] - Carbon dioxide emissions per capita (CDIAC)[EN_ATM_ODS] - Consumption of all ozone-depleting substances[EN_LND_SLUM] - Urban population living in slums[ER_LND_TMPA] - Terrestrial and marine areas protected[ER_LND_TPA] - Terrestrial areas protected[ER_MRN_MPA] - Marine areas protected[IT_SUB_i911] - Mobile cellular telephone subscriptions[IT_SUB_ii91] - Telephone lines[IT_USE_ii99] - Internet users[NR_WTR_WITH] - Total water resources used[PA_NUS_PPP] - Purchasing power parities (PPP) conversion factor[SE_ADT_1524] - Literacy rate[SE_ADT_GPI] - Women to men parity index, as ratio of literacy rates[SE_ENR_NORPH] - School attendance rate of children both of whose parents are alive and who live with at least one parent[SE_ENR_ORPH] - School attendance rate of orphans[SE_ENR_ORPHR] - Ratio of school attendance rate of orphans to school attendance rate of non-orphans[SE_PRM_CMPL] - Primary completion rate[SE_PRM_GPI] - Gender Parity Index in primary level enrolment[SE_PRM_NENR] - Total net enrolment ratio in primary education[SE_PRM_PRSL] - Pupils starting grade 1 who reach last grade of primary[SE_SEC_GPI] - Gender Parity Index in secondary level enrolment[SE_TER_GPI] - Gender Parity Index in tertiary level enrolment[SG_GEN_PARL] - Seats in national parliament[SH_ARV_ACCS] - Antiretroviral therapy coverage among people with advanced HIV infection[SH_ARV_ACCS_LB] - Antiretroviral therapy coverage among people with advanced HIV infection (lower bound)[SH_ARV_ACCS_UB] - Antiretroviral therapy coverage among people with advanced HIV infection (upper bound)[SH_ARV_MTCT] - HIV-infected pregnant women who received antiretroviral drugs to reduce the risk for mother-to-child transmission[SH_ARV_MTCT_LB] - HIV-infected pregnant women who received antiretroviral drugs to reduce the risk for mother-to-child transmission (lower bound)[SH_ARV_MTCT_UB] - HIV-infected pregnant women who received antiretroviral drugs to reduce the risk for mother-to-child transmission (upper bound)[SH_CON_HRSX] - Condom use at last high-risk sex[SH_DYN_AIDS] - AIDS deaths[SH_DYN_AIDS_LB] - AIDS deaths (lower bound)[SH_DYN_AIDS_UB] - AIDS deaths (upper bound)[SH_DYN_IMRT] - Infant mortality rate[SH_DYN_MORT] - Under-five mortality rate[SH_FPL_UNML] - Unmet need for family planning, limiting[SH_FPL_UNMS] - Unmet need for family planning, spacing[SH_FPL_UNMT] - Unmet need for family planning[SH_H2O_IMPR] - Population using improved drinking water sources[SH_HIV_INCD] - HIV incidence rate[SH_HIV_INCD_LB] - HIV incidence rate (lower bound)[SH_HIV_INCD_UB] - HIV incidence rate (upper bound)[SH_HIV_KNOW] - Population with comprehensive correct knowledge of HIV/AIDS[SH_HIV_ORPH] - AIDS orphans[SH_HIV_TOTL] - People living with HIV[SH_HIV_TOTL_LB] - People living with HIV (lower bound)[SH_HIV_TOTL_UB] - People living with HIV (upper bound)[SH_IMM_MEAS] - Children immunized against measles[SH_MLR_MORT] - Malaria death rate[SH_MLR_NETS] - Children sleeping under insecticide-treated bed nets[SH_MLR_TRET] - Children with fever being treated with anti-malarial drugs[SH_SAN_IMPR] - Population using improved sanitation facilities[SH_STA_ANV1] - Antenatal care coverage, at least one visit[SH_STA_ANV4] - Antenatal care coverage, at least four visits[SH_STA_BRTC] - Births attended by skilled health personnel[SH_STA_MALR] - Notified cases of malaria[SH_STA_MORT] - Maternal mortality ratio[SH_TBS_CURE] - Tuberculosis treatment success rate under DOTS[SH_TBS_DOTS] - Tuberculosis detection rate under DOTS[SH_TBS_DOTS_LB] - Tuberculosis detection rate under DOTS (lower bound)[SH_TBS_DOTS_UB] - Tuberculosis detection rate under DOTS (upper bound)[SH_TBS_INCD] - Tuberculosis incidence rate[SH_TBS_INCD_LB] - Tuberculosis incidence rate (lower bound)[SH_TBS_INCD_UB] - Tuberculosis incidence rate (upper bound)[SH_TBS_MORT] - Tuberculosis death rate[SH_TBS_MORT_LB] - Tuberculosis death rate (lower bound)[SH_TBS_MORT_UB] - Tuberculosis death rate (upper bound)[SH_TBS_PREV] - Tuberculosis prevalence rate[SH_TBS_PREV_LB] - Tuberculosis prevalence rate (lower bound)[SH_TBS_PREV_UB] - Tuberculosis prevalence rate (upper bound)[SI_DST_1QNT] - Poorest quintile's share in national income or consumption[SI_POV_DAY1] - Population below USD 1 (PPP) per day[SI_POV_GAP1] - Poverty gap ratio at USD 1 a day (PPP)[SI_POV_NAHC] - Population below national poverty line[SL_EMP_1DAY] - Employed people living below USD 1 (PPP) per day[SL_EMP_NAGR] - Share women in wage employment in the non-agricultural sector[SL_EMP_OACF] - Proportion of own-account and contributing family workers in total employment[SL_EMP_PCAP] - Growth rate of GDP per person employed[SL_EMP_TOTL] - Employment-to-population ratio[SL_UEM_1524] - Youth unemployment rate[SL_UEM_YTOA] - Ratio of youth unemployment rate to adult unemployment rate[SL_UEM_YTOT] - Share of youth unemployed in total unemployed[SL_UEM_YTOY] - Share of youth unemployed in youth population[SN_ITK_DEFC] - Population undernourished[SN_STA_MALN] - Children moderately or severely underweight[SN_STA_MALS] - Children severely underweight[SP_DYN_ADKL] - Adolescent birth rate[SP_DYN_CCON] - Condom use to overall contraceptive use among currently married women[SP_DYN_CONC] - Contraceptive use among married women, condom[SP_DYN_CONM] - Contraceptive use among married women, modern methods[SP_DYN_CONU] - Contraceptive use among married women, any method[TM_VAL_DCDF] - Developed country imports from developing countries, admitted duty free[TM_VAL_LDDF] - Developed country imports from the LDCs, admitted duty free[TT_ASE_TOTG] - Agricultural support estimate for OECD countries as a percentage of their GDP[TT_ASE_TOTL] - Agricultural support estimate for OECD countries"

In [8]:
padrao = re.sub('\[','\n', df_series)
padrao = re.sub('\]',':', padrao)
padrao = re.sub('\-','', padrao)
padrao = re.sub(':',"':'", padrao)
padrao = re.sub('\n',"',\n'", padrao)
padrao = re.sub("'  ","'", padrao)

In [9]:
print(padrao)

',
'AG_LND_FRST':'Land area covered by forest',
'DC_AID_LLDC':'ODA received in landlocked developing countries',
'DC_AID_LLDCG':'ODA received in landlocked developing countries as a percentage of their GNI',
'DC_AID_SIDS':'ODA received in small island developing states',
'DC_AID_SIDSG':'ODA received in small island developing states as a percentage of their GNI',
'DC_HPC_COMR':'Debt relief committed under HIPC Initiative, cumulative',
'DC_HPC_MDRI':'Debt relief delivered in full under MDRI initiative, cumulative',
'DC_HPC_STTS':'Countries that have reached their HIPC decision points and countries that have reached their HIPC completion points (cumulative)',
'DC_ODA_LDCG':'Net ODA to LDCs as a percentage of OECD/DAC donors' GNI',
'DC_ODA_LDCS':'Net ODA to LDCs',
'DC_ODA_SOCL':'ODA to basic social services',
'DC_ODA_SOCP':'ODA to basic social services as a percentage of sectorallocable ODA',
'DC_ODA_TCAP':'ODA provided to help build trade capacity',
'DC_ODA_TOTG':'Net ODA as a percentage of OECD/DAC donors' GNI',
'DC_ODA_TOTL':'Net ODA',
'DC_ODA_UNTD':'ODA that is untied',
'DT_TDS_DECT':'Debt service as percentage of exports of goods and services and net income',
'EG_USE_COMM':'Energy use',
'EG_USE_SLFL':'Population using solid fuels',
'EN_ATM_CFC':'Consumption of ozonedepleting CFCs',
'EN_ATM_CO2':'Carbon dioxide emissions',
'EN_ATM_CO2_CDIAC':'Carbon dioxide emissions (CDIAC)',
'EN_ATM_CO2PC':'Carbon dioxide emissions per capita',
'EN_ATM_CO2PC_CDIAC':'Carbon dioxide emissions per capita (CDIAC)',
'EN_ATM_ODS':'Consumption of all ozonedepleting substances',
'EN_LND_SLUM':'Urban population living in slums',
'ER_LND_TMPA':'Terrestrial and marine areas protected',
'ER_LND_TPA':'Terrestrial areas protected',
'ER_MRN_MPA':'Marine areas protected',
'IT_SUB_i911':'Mobile cellular telephone subscriptions',
'IT_SUB_ii91':'Telephone lines',
'IT_USE_ii99':'Internet users',
'NR_WTR_WITH':'Total water resources used',
'PA_NUS_PPP':'Purchasing power parities (PPP) conversion factor',
'SE_ADT_1524':'Literacy rate',
'SE_ADT_GPI':'Women to men parity index, as ratio of literacy rates',
'SE_ENR_NORPH':'School attendance rate of children both of whose parents are alive and who live with at least one parent',
'SE_ENR_ORPH':'School attendance rate of orphans',
'SE_ENR_ORPHR':'Ratio of school attendance rate of orphans to school attendance rate of nonorphans',
'SE_PRM_CMPL':'Primary completion rate',
'SE_PRM_GPI':'Gender Parity Index in primary level enrolment',
'SE_PRM_NENR':'Total net enrolment ratio in primary education',
'SE_PRM_PRSL':'Pupils starting grade 1 who reach last grade of primary',
'SE_SEC_GPI':'Gender Parity Index in secondary level enrolment',
'SE_TER_GPI':'Gender Parity Index in tertiary level enrolment',
'SG_GEN_PARL':'Seats in national parliament',
'SH_ARV_ACCS':'Antiretroviral therapy coverage among people with advanced HIV infection',
'SH_ARV_ACCS_LB':'Antiretroviral therapy coverage among people with advanced HIV infection (lower bound)',
'SH_ARV_ACCS_UB':'Antiretroviral therapy coverage among people with advanced HIV infection (upper bound)',
'SH_ARV_MTCT':'HIVinfected pregnant women who received antiretroviral drugs to reduce the risk for mothertochild transmission',
'SH_ARV_MTCT_LB':'HIVinfected pregnant women who received antiretroviral drugs to reduce the risk for mothertochild transmission (lower bound)',
'SH_ARV_MTCT_UB':'HIVinfected pregnant women who received antiretroviral drugs to reduce the risk for mothertochild transmission (upper bound)',
'SH_CON_HRSX':'Condom use at last highrisk sex',
'SH_DYN_AIDS':'AIDS deaths',
'SH_DYN_AIDS_LB':'AIDS deaths (lower bound)',
'SH_DYN_AIDS_UB':'AIDS deaths (upper bound)',
'SH_DYN_IMRT':'Infant mortality rate',
'SH_DYN_MORT':'Underfive mortality rate',
'SH_FPL_UNML':'Unmet need for family planning, limiting',
'SH_FPL_UNMS':'Unmet need for family planning, spacing',
'SH_FPL_UNMT':'Unmet need for family planning',
'SH_H2O_IMPR':'Population using improved drinking water sources',
'SH_HIV_INCD':'HIV incidence rate',
'SH_HIV_INCD_LB':'HIV incidence rate (lower bound)',
'SH_HIV_INCD_UB':'HIV incidence rate (upper bound)',
'SH_HIV_KNOW':'Population with comprehensive correct knowledge of HIV/AIDS',
'SH_HIV_ORPH':'AIDS orphans',
'SH_HIV_TOTL':'People living with HIV',
'SH_HIV_TOTL_LB':'People living with HIV (lower bound)',
'SH_HIV_TOTL_UB':'People living with HIV (upper bound)',
'SH_IMM_MEAS':'Children immunized against measles',
'SH_MLR_MORT':'Malaria death rate',
'SH_MLR_NETS':'Children sleeping under insecticidetreated bed nets',
'SH_MLR_TRET':'Children with fever being treated with antimalarial drugs',
'SH_SAN_IMPR':'Population using improved sanitation facilities',
'SH_STA_ANV1':'Antenatal care coverage, at least one visit',
'SH_STA_ANV4':'Antenatal care coverage, at least four visits',
'SH_STA_BRTC':'Births attended by skilled health personnel',
'SH_STA_MALR':'Notified cases of malaria',
'SH_STA_MORT':'Maternal mortality ratio',
'SH_TBS_CURE':'Tuberculosis treatment success rate under DOTS',
'SH_TBS_DOTS':'Tuberculosis detection rate under DOTS',
'SH_TBS_DOTS_LB':'Tuberculosis detection rate under DOTS (lower bound)',
'SH_TBS_DOTS_UB':'Tuberculosis detection rate under DOTS (upper bound)',
'SH_TBS_INCD':'Tuberculosis incidence rate',
'SH_TBS_INCD_LB':'Tuberculosis incidence rate (lower bound)',
'SH_TBS_INCD_UB':'Tuberculosis incidence rate (upper bound)',
'SH_TBS_MORT':'Tuberculosis death rate',
'SH_TBS_MORT_LB':'Tuberculosis death rate (lower bound)',
'SH_TBS_MORT_UB':'Tuberculosis death rate (upper bound)',
'SH_TBS_PREV':'Tuberculosis prevalence rate',
'SH_TBS_PREV_LB':'Tuberculosis prevalence rate (lower bound)',
'SH_TBS_PREV_UB':'Tuberculosis prevalence rate (upper bound)',
'SI_DST_1QNT':'Poorest quintile's share in national income or consumption',
'SI_POV_DAY1':'Population below USD 1 (PPP) per day',
'SI_POV_GAP1':'Poverty gap ratio at USD 1 a day (PPP)',
'SI_POV_NAHC':'Population below national poverty line',
'SL_EMP_1DAY':'Employed people living below USD 1 (PPP) per day',
'SL_EMP_NAGR':'Share women in wage employment in the nonagricultural sector',
'SL_EMP_OACF':'Proportion of ownaccount and contributing family workers in total employment',
'SL_EMP_PCAP':'Growth rate of GDP per person employed',
'SL_EMP_TOTL':'Employmenttopopulation ratio',
'SL_UEM_1524':'Youth unemployment rate',
'SL_UEM_YTOA':'Ratio of youth unemployment rate to adult unemployment rate',
'SL_UEM_YTOT':'Share of youth unemployed in total unemployed',
'SL_UEM_YTOY':'Share of youth unemployed in youth population',
'SN_ITK_DEFC':'Population undernourished',
'SN_STA_MALN':'Children moderately or severely underweight',
'SN_STA_MALS':'Children severely underweight',
'SP_DYN_ADKL':'Adolescent birth rate',
'SP_DYN_CCON':'Condom use to overall contraceptive use among currently married women',
'SP_DYN_CONC':'Contraceptive use among married women, condom',
'SP_DYN_CONM':'Contraceptive use among married women, modern methods',
'SP_DYN_CONU':'Contraceptive use among married women, any method',
'TM_VAL_DCDF':'Developed country imports from developing countries, admitted duty free',
'TM_VAL_LDDF':'Developed country imports from the LDCs, admitted duty free',
'TT_ASE_TOTG':'Agricultural support estimate for OECD countries as a percentage of their GDP',
'TT_ASE_TOTL':'Agricultural support estimate for OECD countries

In [10]:
nacoesunidas['SERIES'] = nacoesunidas['SERIES'].replace({'AG_LND_FRST':'Land area covered by forest',
'DC_AID_LLDC':'ODA received in landlocked developing countries',
'DC_AID_LLDCG':'ODA received in landlocked developing countries as a percentage of their GNI',
'DC_AID_SIDS':'ODA received in small island developing states',
'DC_AID_SIDSG':'ODA received in small island developing states as a percentage of their GNI',
'DC_HPC_COMR':'Debt relief committed under HIPC Initiative, cumulative',
'DC_HPC_MDRI':'Debt relief delivered in full under MDRI initiative, cumulative',
'DC_HPC_STTS':'Countries that have reached their HIPC decision points and countries that have reached their HIPC completion points (cumulative)',
'DC_ODA_LDCG':"Net ODA to LDCs as a percentage of OECD/DAC donors' GNI",
'DC_ODA_LDCS':'Net ODA to LDCs',
'DC_ODA_SOCL':'ODA to basic social services',
'DC_ODA_SOCP':'ODA to basic social services as a percentage of sectorallocable ODA',
'DC_ODA_TCAP':'ODA provided to help build trade capacity',
'DC_ODA_TOTG':"Net ODA as a percentage of OECD/DAC donors' GNI",
'DC_ODA_TOTL':'Net ODA',
'DC_ODA_UNTD':'ODA that is untied',
'DT_TDS_DECT':'Debt service as percentage of exports of goods and services and net income',
'EG_USE_COMM':'Energy use',
'EG_USE_SLFL':'Population using solid fuels',
'EN_ATM_CFC':'Consumption of ozonedepleting CFCs',
'EN_ATM_CO2':'Carbon dioxide emissions',
'EN_ATM_CO2_CDIAC':'Carbon dioxide emissions (CDIAC)',
'EN_ATM_CO2PC':'Carbon dioxide emissions per capita',
'EN_ATM_CO2PC_CDIAC':'Carbon dioxide emissions per capita (CDIAC)',
'EN_ATM_ODS':'Consumption of all ozonedepleting substances',
'EN_LND_SLUM':'Urban population living in slums',
'ER_LND_TMPA':'Terrestrial and marine areas protected',
'ER_LND_TPA':'Terrestrial areas protected',
'ER_MRN_MPA':'Marine areas protected',
'IT_SUB_i911':'Mobile cellular telephone subscriptions',
'IT_SUB_ii91':'Telephone lines',
'IT_USE_ii99':'Internet users',
'NR_WTR_WITH':'Total water resources used',
'PA_NUS_PPP':'Purchasing power parities (PPP) conversion factor',
'SE_ADT_1524':'Literacy rate',
'SE_ADT_GPI':'Women to men parity index, as ratio of literacy rates',
'SE_ENR_NORPH':'School attendance rate of children both of whose parents are alive and who live with at least one parent',
'SE_ENR_ORPH':'School attendance rate of orphans',
'SE_ENR_ORPHR':'Ratio of school attendance rate of orphans to school attendance rate of nonorphans',
'SE_PRM_CMPL':'Primary completion rate',
'SE_PRM_GPI':'Gender Parity Index in primary level enrolment',
'SE_PRM_NENR':'Total net enrolment ratio in primary education',
'SE_PRM_PRSL':'Pupils starting grade 1 who reach last grade of primary',
'SE_SEC_GPI':'Gender Parity Index in secondary level enrolment',
'SE_TER_GPI':'Gender Parity Index in tertiary level enrolment',
'SG_GEN_PARL':'Seats in national parliament',
'SH_ARV_ACCS':'Antiretroviral therapy coverage among people with advanced HIV infection',
'SH_ARV_ACCS_LB':'Antiretroviral therapy coverage among people with advanced HIV infection (lower bound)',
'SH_ARV_ACCS_UB':'Antiretroviral therapy coverage among people with advanced HIV infection (upper bound)',
'SH_ARV_MTCT':'HIVinfected pregnant women who received antiretroviral drugs to reduce the risk for mothertochild transmission',
'SH_ARV_MTCT_LB':'HIVinfected pregnant women who received antiretroviral drugs to reduce the risk for mothertochild transmission (lower bound)',
'SH_ARV_MTCT_UB':'HIVinfected pregnant women who received antiretroviral drugs to reduce the risk for mothertochild transmission (upper bound)',
'SH_CON_HRSX':'Condom use at last highrisk sex',
'SH_DYN_AIDS':'AIDS deaths',
'SH_DYN_AIDS_LB':'AIDS deaths (lower bound)',
'SH_DYN_AIDS_UB':'AIDS deaths (upper bound)',
'SH_DYN_IMRT':'Infant mortality rate',
'SH_DYN_MORT':'Underfive mortality rate',
'SH_FPL_UNML':'Unmet need for family planning, limiting',
'SH_FPL_UNMS':'Unmet need for family planning, spacing',
'SH_FPL_UNMT':'Unmet need for family planning',
'SH_H2O_IMPR':'Population using improved drinking water sources',
'SH_HIV_INCD':'HIV incidence rate',
'SH_HIV_INCD_LB':'HIV incidence rate (lower bound)',
'SH_HIV_INCD_UB':'HIV incidence rate (upper bound)',
'SH_HIV_KNOW':'Population with comprehensive correct knowledge of HIV/AIDS',
'SH_HIV_ORPH':'AIDS orphans',
'SH_HIV_TOTL':'People living with HIV',
'SH_HIV_TOTL_LB':'People living with HIV (lower bound)',
'SH_HIV_TOTL_UB':'People living with HIV (upper bound)',
'SH_IMM_MEAS':'Children immunized against measles',
'SH_MLR_MORT':'Malaria death rate',
'SH_MLR_NETS':'Children sleeping under insecticidetreated bed nets',
'SH_MLR_TRET':'Children with fever being treated with antimalarial drugs',
'SH_SAN_IMPR':'Population using improved sanitation facilities',
'SH_STA_ANV1':'Antenatal care coverage, at least one visit',
'SH_STA_ANV4':'Antenatal care coverage, at least four visits',
'SH_STA_BRTC':'Births attended by skilled health personnel',
'SH_STA_MALR':'Notified cases of malaria',
'SH_STA_MORT':'Maternal mortality ratio',
'SH_TBS_CURE':'Tuberculosis treatment success rate under DOTS',
'SH_TBS_DOTS':'Tuberculosis detection rate under DOTS',
'SH_TBS_DOTS_LB':'Tuberculosis detection rate under DOTS (lower bound)',
'SH_TBS_DOTS_UB':'Tuberculosis detection rate under DOTS (upper bound)',
'SH_TBS_INCD':'Tuberculosis incidence rate',
'SH_TBS_INCD_LB':'Tuberculosis incidence rate (lower bound)',
'SH_TBS_INCD_UB':'Tuberculosis incidence rate (upper bound)',
'SH_TBS_MORT':'Tuberculosis death rate',
'SH_TBS_MORT_LB':'Tuberculosis death rate (lower bound)',
'SH_TBS_MORT_UB':'Tuberculosis death rate (upper bound)',
'SH_TBS_PREV':'Tuberculosis prevalence rate',
'SH_TBS_PREV_LB':'Tuberculosis prevalence rate (lower bound)',
'SH_TBS_PREV_UB':'Tuberculosis prevalence rate (upper bound)',
'SI_DST_1QNT':"Poorest quintile's share in national income or consumption",
'SI_POV_DAY1':'Population below USD 1 (PPP) per day',
'SI_POV_GAP1':'Poverty gap ratio at USD 1 a day (PPP)',
'SI_POV_NAHC':'Population below national poverty line',
'SL_EMP_1DAY':'Employed people living below USD 1 (PPP) per day',
'SL_EMP_NAGR':'Share women in wage employment in the nonagricultural sector',
'SL_EMP_OACF':'Proportion of ownaccount and contributing family workers in total employment',
'SL_EMP_PCAP':'Growth rate of GDP per person employed',
'SL_EMP_TOTL':'Employmenttopopulation ratio',
'SL_UEM_1524':'Youth unemployment rate',
'SL_UEM_YTOA':'Ratio of youth unemployment rate to adult unemployment rate',
'SL_UEM_YTOT':'Share of youth unemployed in total unemployed',
'SL_UEM_YTOY':'Share of youth unemployed in youth population',
'SN_ITK_DEFC':'Population undernourished',
'SN_STA_MALN':'Children moderately or severely underweight',
'SN_STA_MALS':'Children severely underweight',
'SP_DYN_ADKL':'Adolescent birth rate',
'SP_DYN_CCON':'Condom use to overall contraceptive use among currently married women',
'SP_DYN_CONC':'Contraceptive use among married women, condom',
'SP_DYN_CONM':'Contraceptive use among married women, modern methods',
'SP_DYN_CONU':'Contraceptive use among married women, any method',
'TM_VAL_DCDF':'Developed country imports from developing countries, admitted duty free',
'TM_VAL_LDDF':'Developed country imports from the LDCs, admitted duty free',
'TT_ASE_TOTG':'Agricultural support estimate for OECD countries as a percentage of their GDP',
'TT_ASE_TOTL':'Agricultural support estimate for OECD countries'})

In [11]:
nacoesunidas

,DATAFLOW,FREQ,SERIES,UNIT,LOCATION,AGE_GROUP,SEX,REF_AREA,SOURCE_TYPE,TIME_PERIOD,OBS_VALUE,UNIT_MULT,TIME_DETAIL,NATURE,SOURCE_DETAIL,FOOTNOTES
0,IAEG:DF_UNDATA_MDG(1.2),A,Land area covered by forest,PERCENT,T,NaN,NaN,Aruba,NaN,1990,0.000000,0,1990,E,NaN,NaN
1,IAEG:DF_UNDATA_MDG(1.2),A,Land area covered by forest,PERCENT,T,NaN,NaN,Aruba,NaN,2000,0.000000,0,2000,E,NaN,NaN
2,IAEG:DF_UNDATA_MDG(1.2),A,Land area covered by forest,PERCENT,T,NaN,NaN,Aruba,NaN,2005,0.000000,0,2005,E,NaN,NaN
3,IAEG:DF_UNDATA_MDG(1.2),A,Land area covered by forest,PERCENT,T,NaN,NaN,Aruba,NaN,2010,0.000000,0,2010,E,NaN,NaN
4,IAEG:DF_UNDATA_MDG(1.2),A,Land area covered by forest,PERCENT,T,NaN,NaN,Afghanistan,NaN,1990,2.070266,0,1990,E,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387039,IAEG:DF_UNDATA_MDG(1.2),A,Agricultural support estimate for OECD countries,USD,T,NaN,NaN,United States of America,NaN,2009,76164.930000,6,2009,C,NaN,"Based on OECD, PSE/CSE database 2015"
387040,IAEG:DF_UNDATA_MDG(1.2),A,Agricultural support estimate for OECD countries,USD,T,NaN,NaN,United States of America,NaN,2010,76904.280000,6,2010,C,NaN,"Based on OECD, PSE/CSE database 2015"
387041,IAEG:DF_UNDATA_MDG(1.2),A,Agricultural support estimate for OECD countries,USD,T,NaN,NaN,United States of America,NaN,2011,74963.310000,6,2011,C,NaN,"Based on OECD, PSE/CSE database 2015"
387042,IAEG:DF_UNDATA_MDG(1.2),A,Agricultural support estimate for OECD countries,USD,T,NaN,NaN,United States of America,NaN,2012,82048.830000,6,2012,C,NaN,"Based on OECD, PSE/CSE database 2015"
387043,IAEG:DF_UNDATA_MDG(1.2),A,Agricultural support estimate for OECD countries,USD,T,NaN,NaN,United States of America,NaN,2013,83084.310000,6,2013,C,NaN,"Provisional.| Based on OECD, PSE/CSE database ..."

In [12]:
nacoesunidas.columns

Index(['DATAFLOW', 'FREQ', 'SERIES', 'UNIT', 'LOCATION', 'AGE_GROUP', 'SEX',
       'REF_AREA', 'SOURCE_TYPE', 'TIME_PERIOD', 'OBS_VALUE', 'UNIT_MULT',
       'TIME_DETAIL', 'NATURE', 'SOURCE_DETAIL', 'FOOTNOTES'],
      dtype='object')

In [13]:
nacoes_poverty = nacoesunidas.loc[nacoesunidas['SERIES'] == 'Poverty gap ratio at USD 1 a day (PPP)']

In [14]:
nacoes_poverty.isna().sum()

DATAFLOW           0
FREQ               0
SERIES             0
UNIT               0
LOCATION           0
AGE_GROUP          0
SEX                0
REF_AREA           0
SOURCE_TYPE      852
TIME_PERIOD        0
OBS_VALUE          0
UNIT_MULT          0
TIME_DETAIL        0
NATURE             0
SOURCE_DETAIL    852
FOOTNOTES          1
dtype: int64

In [15]:
nacoes_poverty = nacoes_poverty[['SERIES', 'UNIT', 'SEX',
       'REF_AREA', 'TIME_PERIOD', 'OBS_VALUE', 'UNIT_MULT',
       'TIME_DETAIL', 'NATURE', 'FOOTNOTES']]

In [16]:
nacoes_poverty.info()

<class 'pandas.core.frame.DataFrame'>
Index: 852 entries, 320295 to 321146
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   SERIES       852 non-null    object
 1   UNIT         852 non-null    object
 2   SEX          852 non-null    object
 3   REF_AREA     852 non-null    object
 4   TIME_PERIOD  852 non-null    int64
 5   OBS_VALUE    852 non-null    float64
 6   UNIT_MULT    852 non-null    int64
 7   TIME_DETAIL  852 non-null    int64
 8   NATURE       852 non-null    object
 9   FOOTNOTES    851 non-null    object
dtypes: float64(1), int64(3), object(6)
memory usage: 73.2+ KB

In [17]:
nacoes_poverty = nacoes_poverty.drop(['TIME_DETAIL','UNIT_MULT','SEX','NATURE'], axis=1)

In [18]:
nacoes_poverty

,SERIES,UNIT,REF_AREA,TIME_PERIOD,OBS_VALUE,FOOTNOTES
320295,Poverty gap ratio at USD 1 a day (PPP),PERCENT,Angola,2000,29.94,Consumption based. Urban only.
320296,Poverty gap ratio at USD 1 a day (PPP),PERCENT,Angola,2008,16.45,Consumption based.
320297,Poverty gap ratio at USD 1 a day (PPP),PERCENT,Albania,1996,0.02,Consumption based.
320298,Poverty gap ratio at USD 1 a day (PPP),PERCENT,Albania,2002,0.12,Consumption based.
320299,Poverty gap ratio at USD 1 a day (PPP),PERCENT,Albania,2004,0.11,Consumption based.
...,...,...,...,...,...,...
321142,Poverty gap ratio at USD 1 a day (PPP),PERCENT,Zambia,1998,26.94,Consumption based.
321143,Poverty gap ratio at USD 1 a day (PPP),PERCENT,Zambia,2003,27.13,Consumption based.
321144,Poverty gap ratio at USD 1 a day (PPP),PERCENT,Zambia,2004,32.76,Consumption based.
321145,Poverty gap ratio at USD 1 a day (PPP),PERCENT,Zambia,2006,37.02,Consumption based.
321146,Poverty gap ratio at USD 1 a day (PPP),PERCENT,Zambia,2010,41.78,Consumption based.

In [19]:
nacoes_poverty.to_excel(r'C:\Users\carlo\OneDrive\ANALYTICS\ANALYTICS - IRONHACK\PORTFOLIO\PROJETOS\PROJETO_FINAL_CURSO\Nacoes_Unidas\Dados_Nacoes_Unidas\Nacoes_Poverty.xlsx', index=False)

In [21]:
len(nacoes_poverty['REF_AREA'].unique())

124

In [22]:
len(nacoesunidas['REF_AREA'].unique())

228