In [81]:
import pandas as pd
import numpy as np 
import re
import csv

In [3]:
nacoesunidas = pd.read_csv(r'C:\Users\carlo\OneDrive\ANALYTICS\ANALYTICS - IRONHACK\PORTFOLIO\PROJETOS\PROJETO_FINAL_CURSO\Nacoes_Unidas\Dados_Nacoes_Unidas\IAEG+DF_UNDATA_MDG+1.2_2023_05_15_18_02_14.csv', 
                        sep=';',
                        low_memory=False)

In [4]:
nacoesunidas.head()

,DATAFLOW,FREQ,SERIES,UNIT,LOCATION,AGE_GROUP,SEX,REF_AREA,SOURCE_TYPE,TIME_PERIOD,OBS_VALUE,UNIT_MULT,TIME_DETAIL,NATURE,SOURCE_DETAIL,FOOTNOTES
0,IAEG:DF_UNDATA_MDG(1.2),A,AG_LND_FRST,PERCENT,T,NaN,NaN,ABW,NaN,1990,0.000000,0,1990,E,NaN,NaN
1,IAEG:DF_UNDATA_MDG(1.2),A,AG_LND_FRST,PERCENT,T,NaN,NaN,ABW,NaN,2000,0.000000,0,2000,E,NaN,NaN
2,IAEG:DF_UNDATA_MDG(1.2),A,AG_LND_FRST,PERCENT,T,NaN,NaN,ABW,NaN,2005,0.000000,0,2005,E,NaN,NaN
3,IAEG:DF_UNDATA_MDG(1.2),A,AG_LND_FRST,PERCENT,T,NaN,NaN,ABW,NaN,2010,0.000000,0,2010,E,NaN,NaN
4,IAEG:DF_UNDATA_MDG(1.2),A,AG_LND_FRST,PERCENT,T,NaN,NaN,AFG,NaN,1990,2.070266,0,1990,E,NaN,NaN

In [5]:
nacoesunidas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 387044 entries, 0 to 387043
Data columns (total 16 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   DATAFLOW       387044 non-null  object
 1   FREQ           387044 non-null  object
 2   SERIES         387044 non-null  object
 3   UNIT           387044 non-null  object
 4   LOCATION       387044 non-null  object
 5   AGE_GROUP      304147 non-null  object
 6   SEX            302994 non-null  object
 7   REF_AREA       387044 non-null  object
 8   SOURCE_TYPE    0 non-null       float64
 9   TIME_PERIOD    387044 non-null  int64
 10  OBS_VALUE      320677 non-null  float64
 11  UNIT_MULT      387044 non-null  int64
 12  TIME_DETAIL    387044 non-null  int64
 13  NATURE         315236 non-null  object
 14  SOURCE_DETAIL  0 non-null       float64
 15  FOOTNOTES      94713 non-null   object
dtypes: float64(3), int64(3), object(10)
memory usage: 47.2+ MB

In [6]:
nacoesunidas['REF_AREA'] = nacoesunidas['REF_AREA'].replace({  'CAN': 'Canada',
  'CPV': 'Cape Verde',
  'CYM': 'Cayman Islands',
  'CAF': 'Central African Republic',
  'TCD': 'Chad',
  '830': 'Channel Islands',
  'CHL': 'Chile',
  'CHN': 'China',
  'HKG': 'Hong Kong Special Administrative Region of China',
  'MAC': 'Macao Special Administrative Region of China',
  'COL': 'Colombia',
  'COM': 'Comoros',
  'COG': 'Congo',
  'COK': 'Cook Islands',
  'CRI': 'Costa Rica',
  'CIV': "CÃ´te d'Ivoire",
  'HRV': 'Croatia',
  'CUB': 'Cuba',
  'CYP': 'Cyprus',
  'CZE': 'Czech Republic',
  'PRK': "Democratic People's Republic of Korea",
  'COD': 'Democratic Republic of the Congo',
  'DNK': 'Denmark',
  'DJI': 'Djibouti',
  'DMA': 'Dominica',
  'DOM': 'Dominican Republic',
  'ECU': 'Ecuador',
  'EGY': 'Egypt',
  'SLV': 'El Salvador',
  'GNQ': 'Equatorial Guinea',
  'ERI': 'Eritrea',
  'EST': 'Estonia',
  'ETH': 'Ethiopia',
  'FRO': 'Faeroe Islands',
  'FLK': 'Falkland Islands (Malvinas)',
  'FJI': 'Fiji',
  'FIN': 'Finland',
  'FRA': 'France',
  'GUF': 'French Guiana',
  'PYF': 'French Polynesia',
  'GAB': 'Gabon',
  'GMB': 'Gambia',
  'GEO': 'Georgia',
  'DEU': 'Germany',
  'GHA': 'Ghana',
  'GIB': 'Gibraltar',
  'GRC': 'Greece',
  'GRL': 'Greenland',
  'GRD': 'Grenada',
  'GLP': 'Guadeloupe',
  'GUM': 'Guam',
  'GTM': 'Guatemala',
  'GIN': 'Guinea',
  'GNB': 'Guinea-Bissau',
  'GUY': 'Guyana',
  'HTI': 'Haiti',
  'HND': 'Honduras',
  'HUN': 'Hungary',
  'ISL': 'Iceland',
  'IND': 'India',
  'IDN': 'Indonesia',
  'IRN': 'Iran (Islamic Republic of)',
  'IRQ': 'Iraq',
  'IRL': 'Ireland',
  'ISR': 'Israel',
  'ITA': 'Italy',
  'JAM': 'Jamaica',
  'AFG': 'Afghanistan',
  'ALB': 'Albania',
  'DZA': 'Algeria',
  'ASM': 'American Samoa',
  'AND': 'Andorra',
  'AGO': 'Angola',
  'AIA': 'Anguilla',
  'ATG': 'Antigua and Barbuda',
  'ARG': 'Argentina',
  'ARM': 'Armenia',
  'ABW': 'Aruba',
  'AUS': 'Australia',
  'AUT': 'Austria',
  'AZE': 'Azerbaijan',
  'BHS': 'Bahamas',
  'BHR': 'Bahrain',
  'BGD': 'Bangladesh',
  'BRB': 'Barbados',
  'BLR': 'Belarus',
  'BEL': 'Belgium',
  'BLZ': 'Belize',
  'BEN': 'Benin',
  'BMU': 'Bermuda',
  'BTN': 'Bhutan',
  'BOL': 'Bolivia (Plurinational State of)',
  'BIH': 'Bosnia and Herzegovina',
  'BWA': 'Botswana',
  'BRA': 'Brazil',
  'VGB': 'British Virgin Islands',
  'BRN': 'Brunei Darussalam',
  'BGR': 'Bulgaria',
  'BFA': 'Burkina Faso',
  'BDI': 'Burundi',
  'KHM': 'Cambodia',
  'CMR': 'Cameroon',
  'JPN': 'Japan',
  'JOR': 'Jordan',
  'KAZ': 'Kazakhstan',
  'KEN': 'Kenya',
  'KIR': 'Kiribati',
  'KWT': 'Kuwait',
  'KGZ': 'Kyrgyzstan',
  'LAO': "Lao People's Democratic Republic",
  'LVA': 'Latvia',
  'LBN': 'Lebanon',
  'LSO': 'Lesotho',
  'LBR': 'Liberia',
  'LBY': 'Libyan Arab Jamahiriya',
  'LIE': 'Liechtenstein',
  'LTU': 'Lithuania',
  'LUX': 'Luxembourg',
  'MDG': 'Madagascar',
  'MWI': 'Malawi',
  'MYS': 'Malaysia',
  'MDV': 'Maldives',
  'MLI': 'Mali',
  'MLT': 'Malta',
  'MHL': 'Marshall Islands',
  'MTQ': 'Martinique',
  'MRT': 'Mauritania',
  'MUS': 'Mauritius',
  'MYT': 'Mayotte',
  'MEX': 'Mexico',
  'FSM': 'Micronesia (Federated States of)',
  'MDA': 'Republic of Moldova',
  'MCO': 'Monaco',
  'MNG': 'Mongolia',
  'MNE': 'Montenegro',
  'MSR': 'Montserrat',
  'MAR': 'Morocco',
  'MOZ': 'Mozambique',
  'MMR': 'Myanmar',
  'NAM': 'Namibia',
  'NRU': 'Nauru',
  'NPL': 'Nepal',
  'NLD': 'Netherlands',
  'ANT': 'Netherlands Antilles',
  'NCL': 'New Caledonia',
  'NZL': 'New Zealand',
  'NIC': 'Nicaragua',
  'NER': 'Niger',
  'NGA': 'Nigeria',
  'NIU': 'Niue',
  'MNP': 'Northern Mariana Islands',
  'NOR': 'Norway',
  'PSE': 'State of Palestine',
  'OMN': 'Oman',
  'PAK': 'Pakistan',
  'PLW': 'Palau',
  'PAN': 'Panama',
  'PNG': 'Papua New Guinea',
  'PRY': 'Paraguay',
  'PER': 'Peru',
  'PHL': 'Philippines',
  'POL': 'Poland',
  'PRT': 'Portugal',
  'PRI': 'Puerto Rico',
  'QAT': 'Qatar',
  'KOR': 'Republic of Korea',
  'REU': 'RÃ©union',
  'ROU': 'Romania',
  'RUS': 'Russian Federation',
  'RWA': 'Rwanda',
  'SHN': 'Saint Helena',
  'KNA': 'Saint Kitts and Nevis',
  'LCA': 'Saint Lucia',
  'SPM': 'Saint Pierre and Miquelon',
  'VCT': 'Saint Vincent and the Grenadines',
  'WSM': 'Samoa',
  'SMR': 'San Marino',
  'STP': 'Sao Tome and Principe',
  'SAU': 'Saudi Arabia',
  'SEN': 'Senegal',
  'SRB': 'Serbia',
  'SYC': 'Seychelles',
  'SLE': 'Sierra Leone',
  'SGP': 'Singapore',
  'SVK': 'Slovakia',
  'SVN': 'Slovenia',
  'SLB': 'Solomon Islands',
  'SOM': 'Somalia',
  'ZAF': 'South Africa',
  'SSD': 'South Sudan',
  'ESP': 'Spain',
  'LKA': 'Sri Lanka',
  'SDN': 'Sudan',
  'SUR': 'Suriname',
  'SWZ': 'Swaziland',
  'SWE': 'Sweden',
  'CHE': 'Switzerland',
  'SYR': 'Syrian Arab Republic',
  'TJK': 'Tajikistan',
  'THA': 'Thailand',
  'MKD': 'The former Yugoslav Republic of Macedonia',
  'TLS': 'Timor-Leste',
  'TGO': 'Togo',
  'TKL': 'Tokelau',
  'TON': 'Tonga',
  'TTO': 'Trinidad and Tobago',
  'TUN': 'Tunisia',
  'TUR': 'Turkey',
  'TKM': 'Turkmenistan',
  'TCA': 'Turks and Caicos Islands',
  'TUV': 'Tuvalu',
  'UGA': 'Uganda',
  'UKR': 'Ukraine',
  'ARE': 'United Arab Emirates',
  'GBR': 'United Kingdom of Great Britain and Northern Ireland',
  'TZA': 'United Republic of Tanzania',
  'USA': 'United States of America',
  'VIR': 'United States Virgin Islands',
  'URY': 'Uruguay',
  'UZB': 'Uzbekistan',
  'VUT': 'Vanuatu',
  'VEN': 'Venezuela (Bolivarian Republic of)',
  'VNM': 'Viet Nam',
  'WLF': 'Wallis and Futuna Islands',
  'ESH': 'Western Sahara',
  'YEM': 'Yemen',
  'ZMB': 'Zambia',
  'ZWE': 'Zimbabwe'})

In [7]:
nacoesunidas.head()

,DATAFLOW,FREQ,SERIES,UNIT,LOCATION,AGE_GROUP,SEX,REF_AREA,SOURCE_TYPE,TIME_PERIOD,OBS_VALUE,UNIT_MULT,TIME_DETAIL,NATURE,SOURCE_DETAIL,FOOTNOTES
0,IAEG:DF_UNDATA_MDG(1.2),A,AG_LND_FRST,PERCENT,T,NaN,NaN,Aruba,NaN,1990,0.000000,0,1990,E,NaN,NaN
1,IAEG:DF_UNDATA_MDG(1.2),A,AG_LND_FRST,PERCENT,T,NaN,NaN,Aruba,NaN,2000,0.000000,0,2000,E,NaN,NaN
2,IAEG:DF_UNDATA_MDG(1.2),A,AG_LND_FRST,PERCENT,T,NaN,NaN,Aruba,NaN,2005,0.000000,0,2005,E,NaN,NaN
3,IAEG:DF_UNDATA_MDG(1.2),A,AG_LND_FRST,PERCENT,T,NaN,NaN,Aruba,NaN,2010,0.000000,0,2010,E,NaN,NaN
4,IAEG:DF_UNDATA_MDG(1.2),A,AG_LND_FRST,PERCENT,T,NaN,NaN,Afghanistan,NaN,1990,2.070266,0,1990,E,NaN,NaN

In [8]:
df_series = "[AG_LND_FRST] - Land area covered by forest[DC_AID_LLDC] - ODA received in landlocked developing countries[DC_AID_LLDCG] - ODA received in landlocked developing countries as a percentage of their GNI[DC_AID_SIDS] - ODA received in small island developing states[DC_AID_SIDSG] - ODA received in small island developing states as a percentage of their GNI[DC_HPC_COMR] - Debt relief committed under HIPC Initiative, cumulative[DC_HPC_MDRI] - Debt relief delivered in full under MDRI initiative, cumulative[DC_HPC_STTS] - Countries that have reached their HIPC decision points and countries that have reached their HIPC completion points (cumulative)[DC_ODA_LDCG] - Net ODA to LDCs as a percentage of OECD/DAC donors' GNI[DC_ODA_LDCS] - Net ODA to LDCs[DC_ODA_SOCL] - ODA to basic social services[DC_ODA_SOCP] - ODA to basic social services as a percentage of sector-allocable ODA[DC_ODA_TCAP] - ODA provided to help build trade capacity[DC_ODA_TOTG] - Net ODA as a percentage of OECD/DAC donors' GNI[DC_ODA_TOTL] - Net ODA[DC_ODA_UNTD] - ODA that is untied[DT_TDS_DECT] - Debt service as percentage of exports of goods and services and net income[EG_USE_COMM] - Energy use[EG_USE_SLFL] - Population using solid fuels[EN_ATM_CFC] - Consumption of ozone-depleting CFCs[EN_ATM_CO2] - Carbon dioxide emissions[EN_ATM_CO2_CDIAC] - Carbon dioxide emissions (CDIAC)[EN_ATM_CO2PC] - Carbon dioxide emissions per capita[EN_ATM_CO2PC_CDIAC] - Carbon dioxide emissions per capita (CDIAC)[EN_ATM_ODS] - Consumption of all ozone-depleting substances[EN_LND_SLUM] - Urban population living in slums[ER_LND_TMPA] - Terrestrial and marine areas protected[ER_LND_TPA] - Terrestrial areas protected[ER_MRN_MPA] - Marine areas protected[IT_SUB_i911] - Mobile cellular telephone subscriptions[IT_SUB_ii91] - Telephone lines[IT_USE_ii99] - Internet users[NR_WTR_WITH] - Total water resources used[PA_NUS_PPP] - Purchasing power parities (PPP) conversion factor[SE_ADT_1524] - Literacy rate[SE_ADT_GPI] - Women to men parity index, as ratio of literacy rates[SE_ENR_NORPH] - School attendance rate of children both of whose parents are alive and who live with at least one parent[SE_ENR_ORPH] - School attendance rate of orphans[SE_ENR_ORPHR] - Ratio of school attendance rate of orphans to school attendance rate of non-orphans[SE_PRM_CMPL] - Primary completion rate[SE_PRM_GPI] - Gender Parity Index in primary level enrolment[SE_PRM_NENR] - Total net enrolment ratio in primary education[SE_PRM_PRSL] - Pupils starting grade 1 who reach last grade of primary[SE_SEC_GPI] - Gender Parity Index in secondary level enrolment[SE_TER_GPI] - Gender Parity Index in tertiary level enrolment[SG_GEN_PARL] - Seats in national parliament[SH_ARV_ACCS] - Antiretroviral therapy coverage among people with advanced HIV infection[SH_ARV_ACCS_LB] - Antiretroviral therapy coverage among people with advanced HIV infection (lower bound)[SH_ARV_ACCS_UB] - Antiretroviral therapy coverage among people with advanced HIV infection (upper bound)[SH_ARV_MTCT] - HIV-infected pregnant women who received antiretroviral drugs to reduce the risk for mother-to-child transmission[SH_ARV_MTCT_LB] - HIV-infected pregnant women who received antiretroviral drugs to reduce the risk for mother-to-child transmission (lower bound)[SH_ARV_MTCT_UB] - HIV-infected pregnant women who received antiretroviral drugs to reduce the risk for mother-to-child transmission (upper bound)[SH_CON_HRSX] - Condom use at last high-risk sex[SH_DYN_AIDS] - AIDS deaths[SH_DYN_AIDS_LB] - AIDS deaths (lower bound)[SH_DYN_AIDS_UB] - AIDS deaths (upper bound)[SH_DYN_IMRT] - Infant mortality rate[SH_DYN_MORT] - Under-five mortality rate[SH_FPL_UNML] - Unmet need for family planning, limiting[SH_FPL_UNMS] - Unmet need for family planning, spacing[SH_FPL_UNMT] - Unmet need for family planning[SH_H2O_IMPR] - Population using improved drinking water sources[SH_HIV_INCD] - HIV incidence rate[SH_HIV_INCD_LB] - HIV incidence rate (lower bound)[SH_HIV_INCD_UB] - HIV incidence rate (upper bound)[SH_HIV_KNOW] - Population with comprehensive correct knowledge of HIV/AIDS[SH_HIV_ORPH] - AIDS orphans[SH_HIV_TOTL] - People living with HIV[SH_HIV_TOTL_LB] - People living with HIV (lower bound)[SH_HIV_TOTL_UB] - People living with HIV (upper bound)[SH_IMM_MEAS] - Children immunized against measles[SH_MLR_MORT] - Malaria death rate[SH_MLR_NETS] - Children sleeping under insecticide-treated bed nets[SH_MLR_TRET] - Children with fever being treated with anti-malarial drugs[SH_SAN_IMPR] - Population using improved sanitation facilities[SH_STA_ANV1] - Antenatal care coverage, at least one visit[SH_STA_ANV4] - Antenatal care coverage, at least four visits[SH_STA_BRTC] - Births attended by skilled health personnel[SH_STA_MALR] - Notified cases of malaria[SH_STA_MORT] - Maternal mortality ratio[SH_TBS_CURE] - Tuberculosis treatment success rate under DOTS[SH_TBS_DOTS] - Tuberculosis detection rate under DOTS[SH_TBS_DOTS_LB] - Tuberculosis detection rate under DOTS (lower bound)[SH_TBS_DOTS_UB] - Tuberculosis detection rate under DOTS (upper bound)[SH_TBS_INCD] - Tuberculosis incidence rate[SH_TBS_INCD_LB] - Tuberculosis incidence rate (lower bound)[SH_TBS_INCD_UB] - Tuberculosis incidence rate (upper bound)[SH_TBS_MORT] - Tuberculosis death rate[SH_TBS_MORT_LB] - Tuberculosis death rate (lower bound)[SH_TBS_MORT_UB] - Tuberculosis death rate (upper bound)[SH_TBS_PREV] - Tuberculosis prevalence rate[SH_TBS_PREV_LB] - Tuberculosis prevalence rate (lower bound)[SH_TBS_PREV_UB] - Tuberculosis prevalence rate (upper bound)[SI_DST_1QNT] - Poorest quintile's share in national income or consumption[SI_POV_DAY1] - Population below USD 1 (PPP) per day[SI_POV_GAP1] - Poverty gap ratio at USD 1 a day (PPP)[SI_POV_NAHC] - Population below national poverty line[SL_EMP_1DAY] - Employed people living below USD 1 (PPP) per day[SL_EMP_NAGR] - Share women in wage employment in the non-agricultural sector[SL_EMP_OACF] - Proportion of own-account and contributing family workers in total employment[SL_EMP_PCAP] - Growth rate of GDP per person employed[SL_EMP_TOTL] - Employment-to-population ratio[SL_UEM_1524] - Youth unemployment rate[SL_UEM_YTOA] - Ratio of youth unemployment rate to adult unemployment rate[SL_UEM_YTOT] - Share of youth unemployed in total unemployed[SL_UEM_YTOY] - Share of youth unemployed in youth population[SN_ITK_DEFC] - Population undernourished[SN_STA_MALN] - Children moderately or severely underweight[SN_STA_MALS] - Children severely underweight[SP_DYN_ADKL] - Adolescent birth rate[SP_DYN_CCON] - Condom use to overall contraceptive use among currently married women[SP_DYN_CONC] - Contraceptive use among married women, condom[SP_DYN_CONM] - Contraceptive use among married women, modern methods[SP_DYN_CONU] - Contraceptive use among married women, any method[TM_VAL_DCDF] - Developed country imports from developing countries, admitted duty free[TM_VAL_LDDF] - Developed country imports from the LDCs, admitted duty free[TT_ASE_TOTG] - Agricultural support estimate for OECD countries as a percentage of their GDP[TT_ASE_TOTL] - Agricultural support estimate for OECD countries"

In [9]:
padrao = re.sub('\[','\n', df_series)
padrao = re.sub('\]',':', padrao)
padrao = re.sub('\-','', padrao)
padrao = re.sub(':',"':'", padrao)
padrao = re.sub('\n',"',\n'", padrao)
padrao = re.sub("'  ","'", padrao)

In [10]:
print(padrao)

',
'AG_LND_FRST':'Land area covered by forest',
'DC_AID_LLDC':'ODA received in landlocked developing countries',
'DC_AID_LLDCG':'ODA received in landlocked developing countries as a percentage of their GNI',
'DC_AID_SIDS':'ODA received in small island developing states',
'DC_AID_SIDSG':'ODA received in small island developing states as a percentage of their GNI',
'DC_HPC_COMR':'Debt relief committed under HIPC Initiative, cumulative',
'DC_HPC_MDRI':'Debt relief delivered in full under MDRI initiative, cumulative',
'DC_HPC_STTS':'Countries that have reached their HIPC decision points and countries that have reached their HIPC completion points (cumulative)',
'DC_ODA_LDCG':'Net ODA to LDCs as a percentage of OECD/DAC donors' GNI',
'DC_ODA_LDCS':'Net ODA to LDCs',
'DC_ODA_SOCL':'ODA to basic social services',
'DC_ODA_SOCP':'ODA to basic social services as a percentage of sectorallocable ODA',
'DC_ODA_TCAP':'ODA provided to help build trade capacity',
'DC_ODA_TOTG':'Net ODA as a percentage of OECD/DAC donors' GNI',
'DC_ODA_TOTL':'Net ODA',
'DC_ODA_UNTD':'ODA that is untied',
'DT_TDS_DECT':'Debt service as percentage of exports of goods and services and net income',
'EG_USE_COMM':'Energy use',
'EG_USE_SLFL':'Population using solid fuels',
'EN_ATM_CFC':'Consumption of ozonedepleting CFCs',
'EN_ATM_CO2':'Carbon dioxide emissions',
'EN_ATM_CO2_CDIAC':'Carbon dioxide emissions (CDIAC)',
'EN_ATM_CO2PC':'Carbon dioxide emissions per capita',
'EN_ATM_CO2PC_CDIAC':'Carbon dioxide emissions per capita (CDIAC)',
'EN_ATM_ODS':'Consumption of all ozonedepleting substances',
'EN_LND_SLUM':'Urban population living in slums',
'ER_LND_TMPA':'Terrestrial and marine areas protected',
'ER_LND_TPA':'Terrestrial areas protected',
'ER_MRN_MPA':'Marine areas protected',
'IT_SUB_i911':'Mobile cellular telephone subscriptions',
'IT_SUB_ii91':'Telephone lines',
'IT_USE_ii99':'Internet users',
'NR_WTR_WITH':'Total water resources used',
'PA_NUS_PPP':'Purchasing power parities (PPP) conversion factor',
'SE_ADT_1524':'Literacy rate',
'SE_ADT_GPI':'Women to men parity index, as ratio of literacy rates',
'SE_ENR_NORPH':'School attendance rate of children both of whose parents are alive and who live with at least one parent',
'SE_ENR_ORPH':'School attendance rate of orphans',
'SE_ENR_ORPHR':'Ratio of school attendance rate of orphans to school attendance rate of nonorphans',
'SE_PRM_CMPL':'Primary completion rate',
'SE_PRM_GPI':'Gender Parity Index in primary level enrolment',
'SE_PRM_NENR':'Total net enrolment ratio in primary education',
'SE_PRM_PRSL':'Pupils starting grade 1 who reach last grade of primary',
'SE_SEC_GPI':'Gender Parity Index in secondary level enrolment',
'SE_TER_GPI':'Gender Parity Index in tertiary level enrolment',
'SG_GEN_PARL':'Seats in national parliament',
'SH_ARV_ACCS':'Antiretroviral therapy coverage among people with advanced HIV infection',
'SH_ARV_ACCS_LB':'Antiretroviral therapy coverage among people with advanced HIV infection (lower bound)',
'SH_ARV_ACCS_UB':'Antiretroviral therapy coverage among people with advanced HIV infection (upper bound)',
'SH_ARV_MTCT':'HIVinfected pregnant women who received antiretroviral drugs to reduce the risk for mothertochild transmission',
'SH_ARV_MTCT_LB':'HIVinfected pregnant women who received antiretroviral drugs to reduce the risk for mothertochild transmission (lower bound)',
'SH_ARV_MTCT_UB':'HIVinfected pregnant women who received antiretroviral drugs to reduce the risk for mothertochild transmission (upper bound)',
'SH_CON_HRSX':'Condom use at last highrisk sex',
'SH_DYN_AIDS':'AIDS deaths',
'SH_DYN_AIDS_LB':'AIDS deaths (lower bound)',
'SH_DYN_AIDS_UB':'AIDS deaths (upper bound)',
'SH_DYN_IMRT':'Infant mortality rate',
'SH_DYN_MORT':'Underfive mortality rate',
'SH_FPL_UNML':'Unmet need for family planning, limiting',
'SH_FPL_UNMS':'Unmet need for family planning, spacing',
'SH_FPL_UNMT':'Unmet need for family planning',
'SH_H2O_IMPR':'Population using improved drinking water sources',
'SH_HIV_INCD':'HIV incidence rate',
'SH_HIV_INCD_LB':'HIV incidence rate (lower bound)',
'SH_HIV_INCD_UB':'HIV incidence rate (upper bound)',
'SH_HIV_KNOW':'Population with comprehensive correct knowledge of HIV/AIDS',
'SH_HIV_ORPH':'AIDS orphans',
'SH_HIV_TOTL':'People living with HIV',
'SH_HIV_TOTL_LB':'People living with HIV (lower bound)',
'SH_HIV_TOTL_UB':'People living with HIV (upper bound)',
'SH_IMM_MEAS':'Children immunized against measles',
'SH_MLR_MORT':'Malaria death rate',
'SH_MLR_NETS':'Children sleeping under insecticidetreated bed nets',
'SH_MLR_TRET':'Children with fever being treated with antimalarial drugs',
'SH_SAN_IMPR':'Population using improved sanitation facilities',
'SH_STA_ANV1':'Antenatal care coverage, at least one visit',
'SH_STA_ANV4':'Antenatal care coverage, at least four visits',
'SH_STA_BRTC':'Births attended by skilled health personnel',
'SH_STA_MALR':'Notified cases of malaria',
'SH_STA_MORT':'Maternal mortality ratio',
'SH_TBS_CURE':'Tuberculosis treatment success rate under DOTS',
'SH_TBS_DOTS':'Tuberculosis detection rate under DOTS',
'SH_TBS_DOTS_LB':'Tuberculosis detection rate under DOTS (lower bound)',
'SH_TBS_DOTS_UB':'Tuberculosis detection rate under DOTS (upper bound)',
'SH_TBS_INCD':'Tuberculosis incidence rate',
'SH_TBS_INCD_LB':'Tuberculosis incidence rate (lower bound)',
'SH_TBS_INCD_UB':'Tuberculosis incidence rate (upper bound)',
'SH_TBS_MORT':'Tuberculosis death rate',
'SH_TBS_MORT_LB':'Tuberculosis death rate (lower bound)',
'SH_TBS_MORT_UB':'Tuberculosis death rate (upper bound)',
'SH_TBS_PREV':'Tuberculosis prevalence rate',
'SH_TBS_PREV_LB':'Tuberculosis prevalence rate (lower bound)',
'SH_TBS_PREV_UB':'Tuberculosis prevalence rate (upper bound)',
'SI_DST_1QNT':'Poorest quintile's share in national income or consumption',
'SI_POV_DAY1':'Population below USD 1 (PPP) per day',
'SI_POV_GAP1':'Poverty gap ratio at USD 1 a day (PPP)',
'SI_POV_NAHC':'Population below national poverty line',
'SL_EMP_1DAY':'Employed people living below USD 1 (PPP) per day',
'SL_EMP_NAGR':'Share women in wage employment in the nonagricultural sector',
'SL_EMP_OACF':'Proportion of ownaccount and contributing family workers in total employment',
'SL_EMP_PCAP':'Growth rate of GDP per person employed',
'SL_EMP_TOTL':'Employmenttopopulation ratio',
'SL_UEM_1524':'Youth unemployment rate',
'SL_UEM_YTOA':'Ratio of youth unemployment rate to adult unemployment rate',
'SL_UEM_YTOT':'Share of youth unemployed in total unemployed',
'SL_UEM_YTOY':'Share of youth unemployed in youth population',
'SN_ITK_DEFC':'Population undernourished',
'SN_STA_MALN':'Children moderately or severely underweight',
'SN_STA_MALS':'Children severely underweight',
'SP_DYN_ADKL':'Adolescent birth rate',
'SP_DYN_CCON':'Condom use to overall contraceptive use among currently married women',
'SP_DYN_CONC':'Contraceptive use among married women, condom',
'SP_DYN_CONM':'Contraceptive use among married women, modern methods',
'SP_DYN_CONU':'Contraceptive use among married women, any method',
'TM_VAL_DCDF':'Developed country imports from developing countries, admitted duty free',
'TM_VAL_LDDF':'Developed country imports from the LDCs, admitted duty free',
'TT_ASE_TOTG':'Agricultural support estimate for OECD countries as a percentage of their GDP',
'TT_ASE_TOTL':'Agricultural support estimate for OECD countries

In [11]:
nacoesunidas['SERIES'] = nacoesunidas['SERIES'].replace({'AG_LND_FRST':'Land area covered by forest',
'DC_AID_LLDC':'ODA received in landlocked developing countries',
'DC_AID_LLDCG':'ODA received in landlocked developing countries as a percentage of their GNI',
'DC_AID_SIDS':'ODA received in small island developing states',
'DC_AID_SIDSG':'ODA received in small island developing states as a percentage of their GNI',
'DC_HPC_COMR':'Debt relief committed under HIPC Initiative, cumulative',
'DC_HPC_MDRI':'Debt relief delivered in full under MDRI initiative, cumulative',
'DC_HPC_STTS':'Countries that have reached their HIPC decision points and countries that have reached their HIPC completion points (cumulative)',
'DC_ODA_LDCG':"Net ODA to LDCs as a percentage of OECD/DAC donors' GNI",
'DC_ODA_LDCS':'Net ODA to LDCs',
'DC_ODA_SOCL':'ODA to basic social services',
'DC_ODA_SOCP':'ODA to basic social services as a percentage of sectorallocable ODA',
'DC_ODA_TCAP':'ODA provided to help build trade capacity',
'DC_ODA_TOTG':"Net ODA as a percentage of OECD/DAC donors' GNI",
'DC_ODA_TOTL':'Net ODA',
'DC_ODA_UNTD':'ODA that is untied',
'DT_TDS_DECT':'Debt service as percentage of exports of goods and services and net income',
'EG_USE_COMM':'Energy use',
'EG_USE_SLFL':'Population using solid fuels',
'EN_ATM_CFC':'Consumption of ozonedepleting CFCs',
'EN_ATM_CO2':'Carbon dioxide emissions',
'EN_ATM_CO2_CDIAC':'Carbon dioxide emissions (CDIAC)',
'EN_ATM_CO2PC':'Carbon dioxide emissions per capita',
'EN_ATM_CO2PC_CDIAC':'Carbon dioxide emissions per capita (CDIAC)',
'EN_ATM_ODS':'Consumption of all ozonedepleting substances',
'EN_LND_SLUM':'Urban population living in slums',
'ER_LND_TMPA':'Terrestrial and marine areas protected',
'ER_LND_TPA':'Terrestrial areas protected',
'ER_MRN_MPA':'Marine areas protected',
'IT_SUB_i911':'Mobile cellular telephone subscriptions',
'IT_SUB_ii91':'Telephone lines',
'IT_USE_ii99':'Internet users',
'NR_WTR_WITH':'Total water resources used',
'PA_NUS_PPP':'Purchasing power parities (PPP) conversion factor',
'SE_ADT_1524':'Literacy rate',
'SE_ADT_GPI':'Women to men parity index, as ratio of literacy rates',
'SE_ENR_NORPH':'School attendance rate of children both of whose parents are alive and who live with at least one parent',
'SE_ENR_ORPH':'School attendance rate of orphans',
'SE_ENR_ORPHR':'Ratio of school attendance rate of orphans to school attendance rate of nonorphans',
'SE_PRM_CMPL':'Primary completion rate',
'SE_PRM_GPI':'Gender Parity Index in primary level enrolment',
'SE_PRM_NENR':'Total net enrolment ratio in primary education',
'SE_PRM_PRSL':'Pupils starting grade 1 who reach last grade of primary',
'SE_SEC_GPI':'Gender Parity Index in secondary level enrolment',
'SE_TER_GPI':'Gender Parity Index in tertiary level enrolment',
'SG_GEN_PARL':'Seats in national parliament',
'SH_ARV_ACCS':'Antiretroviral therapy coverage among people with advanced HIV infection',
'SH_ARV_ACCS_LB':'Antiretroviral therapy coverage among people with advanced HIV infection (lower bound)',
'SH_ARV_ACCS_UB':'Antiretroviral therapy coverage among people with advanced HIV infection (upper bound)',
'SH_ARV_MTCT':'HIVinfected pregnant women who received antiretroviral drugs to reduce the risk for mothertochild transmission',
'SH_ARV_MTCT_LB':'HIVinfected pregnant women who received antiretroviral drugs to reduce the risk for mothertochild transmission (lower bound)',
'SH_ARV_MTCT_UB':'HIVinfected pregnant women who received antiretroviral drugs to reduce the risk for mothertochild transmission (upper bound)',
'SH_CON_HRSX':'Condom use at last highrisk sex',
'SH_DYN_AIDS':'AIDS deaths',
'SH_DYN_AIDS_LB':'AIDS deaths (lower bound)',
'SH_DYN_AIDS_UB':'AIDS deaths (upper bound)',
'SH_DYN_IMRT':'Infant mortality rate',
'SH_DYN_MORT':'Underfive mortality rate',
'SH_FPL_UNML':'Unmet need for family planning, limiting',
'SH_FPL_UNMS':'Unmet need for family planning, spacing',
'SH_FPL_UNMT':'Unmet need for family planning',
'SH_H2O_IMPR':'Population using improved drinking water sources',
'SH_HIV_INCD':'HIV incidence rate',
'SH_HIV_INCD_LB':'HIV incidence rate (lower bound)',
'SH_HIV_INCD_UB':'HIV incidence rate (upper bound)',
'SH_HIV_KNOW':'Population with comprehensive correct knowledge of HIV/AIDS',
'SH_HIV_ORPH':'AIDS orphans',
'SH_HIV_TOTL':'People living with HIV',
'SH_HIV_TOTL_LB':'People living with HIV (lower bound)',
'SH_HIV_TOTL_UB':'People living with HIV (upper bound)',
'SH_IMM_MEAS':'Children immunized against measles',
'SH_MLR_MORT':'Malaria death rate',
'SH_MLR_NETS':'Children sleeping under insecticidetreated bed nets',
'SH_MLR_TRET':'Children with fever being treated with antimalarial drugs',
'SH_SAN_IMPR':'Population using improved sanitation facilities',
'SH_STA_ANV1':'Antenatal care coverage, at least one visit',
'SH_STA_ANV4':'Antenatal care coverage, at least four visits',
'SH_STA_BRTC':'Births attended by skilled health personnel',
'SH_STA_MALR':'Notified cases of malaria',
'SH_STA_MORT':'Maternal mortality ratio',
'SH_TBS_CURE':'Tuberculosis treatment success rate under DOTS',
'SH_TBS_DOTS':'Tuberculosis detection rate under DOTS',
'SH_TBS_DOTS_LB':'Tuberculosis detection rate under DOTS (lower bound)',
'SH_TBS_DOTS_UB':'Tuberculosis detection rate under DOTS (upper bound)',
'SH_TBS_INCD':'Tuberculosis incidence rate',
'SH_TBS_INCD_LB':'Tuberculosis incidence rate (lower bound)',
'SH_TBS_INCD_UB':'Tuberculosis incidence rate (upper bound)',
'SH_TBS_MORT':'Tuberculosis death rate',
'SH_TBS_MORT_LB':'Tuberculosis death rate (lower bound)',
'SH_TBS_MORT_UB':'Tuberculosis death rate (upper bound)',
'SH_TBS_PREV':'Tuberculosis prevalence rate',
'SH_TBS_PREV_LB':'Tuberculosis prevalence rate (lower bound)',
'SH_TBS_PREV_UB':'Tuberculosis prevalence rate (upper bound)',
'SI_DST_1QNT':"Poorest quintile's share in national income or consumption",
'SI_POV_DAY1':'Population below USD 1 (PPP) per day',
'SI_POV_GAP1':'Poverty gap ratio at USD 1 a day (PPP)',
'SI_POV_NAHC':'Population below national poverty line',
'SL_EMP_1DAY':'Employed people living below USD 1 (PPP) per day',
'SL_EMP_NAGR':'Share women in wage employment in the nonagricultural sector',
'SL_EMP_OACF':'Proportion of ownaccount and contributing family workers in total employment',
'SL_EMP_PCAP':'Growth rate of GDP per person employed',
'SL_EMP_TOTL':'Employmenttopopulation ratio',
'SL_UEM_1524':'Youth unemployment rate',
'SL_UEM_YTOA':'Ratio of youth unemployment rate to adult unemployment rate',
'SL_UEM_YTOT':'Share of youth unemployed in total unemployed',
'SL_UEM_YTOY':'Share of youth unemployed in youth population',
'SN_ITK_DEFC':'Population undernourished',
'SN_STA_MALN':'Children moderately or severely underweight',
'SN_STA_MALS':'Children severely underweight',
'SP_DYN_ADKL':'Adolescent birth rate',
'SP_DYN_CCON':'Condom use to overall contraceptive use among currently married women',
'SP_DYN_CONC':'Contraceptive use among married women, condom',
'SP_DYN_CONM':'Contraceptive use among married women, modern methods',
'SP_DYN_CONU':'Contraceptive use among married women, any method',
'TM_VAL_DCDF':'Developed country imports from developing countries, admitted duty free',
'TM_VAL_LDDF':'Developed country imports from the LDCs, admitted duty free',
'TT_ASE_TOTG':'Agricultural support estimate for OECD countries as a percentage of their GDP',
'TT_ASE_TOTL':'Agricultural support estimate for OECD countries'})

In [12]:
nacoesunidas

,DATAFLOW,FREQ,SERIES,UNIT,LOCATION,AGE_GROUP,SEX,REF_AREA,SOURCE_TYPE,TIME_PERIOD,OBS_VALUE,UNIT_MULT,TIME_DETAIL,NATURE,SOURCE_DETAIL,FOOTNOTES
0,IAEG:DF_UNDATA_MDG(1.2),A,Land area covered by forest,PERCENT,T,NaN,NaN,Aruba,NaN,1990,0.000000,0,1990,E,NaN,NaN
1,IAEG:DF_UNDATA_MDG(1.2),A,Land area covered by forest,PERCENT,T,NaN,NaN,Aruba,NaN,2000,0.000000,0,2000,E,NaN,NaN
2,IAEG:DF_UNDATA_MDG(1.2),A,Land area covered by forest,PERCENT,T,NaN,NaN,Aruba,NaN,2005,0.000000,0,2005,E,NaN,NaN
3,IAEG:DF_UNDATA_MDG(1.2),A,Land area covered by forest,PERCENT,T,NaN,NaN,Aruba,NaN,2010,0.000000,0,2010,E,NaN,NaN
4,IAEG:DF_UNDATA_MDG(1.2),A,Land area covered by forest,PERCENT,T,NaN,NaN,Afghanistan,NaN,1990,2.070266,0,1990,E,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387039,IAEG:DF_UNDATA_MDG(1.2),A,Agricultural support estimate for OECD countries,USD,T,NaN,NaN,United States of America,NaN,2009,76164.930000,6,2009,C,NaN,"Based on OECD, PSE/CSE database 2015"
387040,IAEG:DF_UNDATA_MDG(1.2),A,Agricultural support estimate for OECD countries,USD,T,NaN,NaN,United States of America,NaN,2010,76904.280000,6,2010,C,NaN,"Based on OECD, PSE/CSE database 2015"
387041,IAEG:DF_UNDATA_MDG(1.2),A,Agricultural support estimate for OECD countries,USD,T,NaN,NaN,United States of America,NaN,2011,74963.310000,6,2011,C,NaN,"Based on OECD, PSE/CSE database 2015"
387042,IAEG:DF_UNDATA_MDG(1.2),A,Agricultural support estimate for OECD countries,USD,T,NaN,NaN,United States of America,NaN,2012,82048.830000,6,2012,C,NaN,"Based on OECD, PSE/CSE database 2015"
387043,IAEG:DF_UNDATA_MDG(1.2),A,Agricultural support estimate for OECD countries,USD,T,NaN,NaN,United States of America,NaN,2013,83084.310000,6,2013,C,NaN,"Provisional.| Based on OECD, PSE/CSE database ..."

In [13]:
nacoesunidas.columns

Index(['DATAFLOW', 'FREQ', 'SERIES', 'UNIT', 'LOCATION', 'AGE_GROUP', 'SEX',
       'REF_AREA', 'SOURCE_TYPE', 'TIME_PERIOD', 'OBS_VALUE', 'UNIT_MULT',
       'TIME_DETAIL', 'NATURE', 'SOURCE_DETAIL', 'FOOTNOTES'],
      dtype='object')

In [37]:
nacoes_poverty = nacoesunidas.loc[nacoesunidas['SERIES'] == 'Poverty gap ratio at USD 1 a day (PPP)']

In [38]:
nacoes_poverty.isna().sum()

DATAFLOW           0
FREQ               0
SERIES             0
UNIT               0
LOCATION           0
AGE_GROUP          0
SEX                0
REF_AREA           0
SOURCE_TYPE      852
TIME_PERIOD        0
OBS_VALUE          0
UNIT_MULT          0
TIME_DETAIL        0
NATURE             0
SOURCE_DETAIL    852
FOOTNOTES          1
dtype: int64

In [39]:
nacoes_poverty = nacoes_poverty[['SERIES','REF_AREA','UNIT','OBS_VALUE','TIME_PERIOD']]

In [43]:
nacoes_poverty.info()

<class 'pandas.core.frame.DataFrame'>
Index: 852 entries, 320295 to 321146
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   SERIES       852 non-null    object
 1   REF_AREA     852 non-null    object
 2   UNIT         852 non-null    object
 3   OBS_VALUE    852 non-null    float64
 4   TIME_PERIOD  852 non-null    int64
dtypes: float64(1), int64(1), object(3)
memory usage: 39.9+ KB

In [50]:
nacoes_poverty = nacoes_poverty.rename(columns={'SERIES':'INDICADOR','REF_AREA':'PAIS','UNIT':'UNIDADE','OBS_VALUE':'VALOR','TIME_PERIOD':'ANO'})

In [52]:
nacoes_poverty.head()

                                     INDICADOR     PAIS  UNIDADE  VALOR   ANO
320295  Poverty gap ratio at USD 1 a day (PPP)   Angola  PERCENT  29.94  2000
320296  Poverty gap ratio at USD 1 a day (PPP)   Angola  PERCENT  16.45  2008
320297  Poverty gap ratio at USD 1 a day (PPP)  Albania  PERCENT   0.02  1996
320298  Poverty gap ratio at USD 1 a day (PPP)  Albania  PERCENT   0.12  2002
320299  Poverty gap ratio at USD 1 a day (PPP)  Albania  PERCENT   0.11  2004

In [20]:
# nacoes_poverty.to_excel(r'C:\Users\carlo\OneDrive\ANALYTICS\ANALYTICS - IRONHACK\PORTFOLIO\PROJETOS\PROJETO_FINAL_CURSO\Nacoes_Unidas\Dados_Nacoes_Unidas\Nacoes_Poverty.xlsx', index=False)

In [53]:
len(nacoes_poverty['PAIS'].unique())

124

In [54]:
len(nacoesunidas['REF_AREA'].unique())

228

In [57]:
nacoesunidas_2 = pd.read_csv(r'C:\Users\carlo\OneDrive\ANALYTICS\ANALYTICS - IRONHACK\PORTFOLIO\PROJETOS\PROJETO_FINAL_CURSO\Nacoes_Unidas\Dados_Nacoes_Unidas\COLUNAS_SEPARADAS_2_IAEG-SDGs+DF_SDG_GLH+1.13_2023_05_18_01_13_13.csv', 
                        sep=';',
                        low_memory=False)

In [58]:
nacoesunidas_2.head()

              INDICADOR  PAIS   ANO    VALOR UNIDADE
0  BX_KLT_DINV_WD_GD_ZS     1  1970  0.47921      PT
1  BX_KLT_DINV_WD_GD_ZS     1  1971   0.4702      PT
2  BX_KLT_DINV_WD_GD_ZS     1  1972  0.42351      PT
3  BX_KLT_DINV_WD_GD_ZS     1  1973  0.47988      PT
4  BX_KLT_DINV_WD_GD_ZS     1  1974  0.49684      PT

In [59]:
nacoesunidas_2['INDICADOR'] = nacoesunidas_2['INDICADOR'].replace({'SI_POV_NAHC':'Proportion of population living below the national poverty line [1.2.1]',
'SI_COV_UEMP':'Proportion of unemployed persons receiving unemployment cash benefit [1.3.1]',
'SI_COV_VULN':'Proportion of vulnerable population receiving social assistance cash benefit [1.3.1]',
'SP_ACS_BSRVSAN':'Proportion of population using basic sanitation services [1.4.1]',
'SP_ACS_BSRVH2O':'Proportion of population using basic drinking water services [1.4.1]',
'SN_ITK_DEFC':'Prevalence of undernourishment [2.1.1]',
'SN_ITK_DEFCN':'Number of undernourish people [2.1.1]',
'SH_STA_BRTC':'Proportion of births attended by skilled health personnel [3.1.2]',
'SH_DYN_IMRT':'Infant mortality rate [3.2.1]',
'SH_DTH_NCOM':'Mortality rate attributed to cardiovascular disease, cancer, diabetes or chronic respiratory disease [3.4.1]',
'SH_ALC_CONSPT':'Alcohol consumption per capita (aged 15 years and older) within a calendar year [3.5.2]',
'SH_STA_WASHARI':'Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene from diarrhoea, intestinal nematode infections, malnutrition and acute respiratory infections [3.9.2]',
'SH_MED_DEN':'Health worker density, by type of occupation (per 10,000 population) [3.c.1]',
'SH_MED_HWRKDIS':'Health worker distribution, by sex and type of occupation [3.c.1]',
'SE_ADT_EDUCTRN':'Participation rate in formal and non-formal education and training [4.3.1]',
'SE_ADT_ACTS':'Proportion of youth and adults with information and communications technology (ICT) skills [4.4.1]',
'SE_GPI_PART':'Adjusted gender parity index for participation rate in formal and non-formal education and training (ratio) [4.5.1]',
'SE_GPI_ICTS':'Gender parity index for youth/adults with information and communications technology (ICT) skills [4.5.1]',
'VC_VAW_MARR':'Proportion of ever-partnered women and girls subjected to physical and sexual violence by a current or former intimate partner in the previous 12 months [5.2.1]',
'SG_GEN_LOCGELS':'Proportion of elected seats held by women in deliberative bodies of local government [5.5.1]',
'SG_GEN_PARL':'Proportion of seats held by women in national parliaments (% of total number of seats) [5.5.1]',
'SG_GEN_PARLN':'Number of seats held by women in national parliaments [5.5.1]',
'SG_GEN_PARLNT':'Current number of seats in national parliaments [5.5.1]',
'IT_MOB_OWN':'Proportion of individuals who own a mobile telephone [5.b.1]',
'EG_ACS_ELEC':'Proportion of population with access to electricity [7.1.1]',
'EG_FEC_RNEW':'Renewable energy share in the total final energy consumption [7.2.1]',
'NY_GDP_PCAP':'Annual growth rate of real GDP per capita [8.1.1]',
'SL_EMP_PCAP':'Annual growth rate of real GDP per employed person [8.2.1]',
'SL_EMP_EARN':'Average hourly earnings [8.5.1]',
'SL_TLF_UEM':'Unemployment rate, by sex and age - 13th ICLS (%) [8.5.2]',
'BX_KLT_DINV_WD_GD_ZS':'Foreign direct investment, net inflows, as a proportion of GDP (%) [17.13.1]',
'NY_GDP_MKTP_KD_ZG':'Annual GDP growth (%) [17.13.1]',
'FP_CPI_TOTL_ZG':'Annual inflation, consumer prices (%) [17.13.1]',
'TG_VAL_TOTL_GD_ZS':'Merchandise trade as a proportion of GDP (%) [17.13.1]'})

In [62]:
nacoesunidas_2.head()

,INDICADOR,PAIS,ANO,VALOR,UNIDADE
0,"Foreign direct investment, net inflows, as a p...",1,1970,0.47921,PT
1,"Foreign direct investment, net inflows, as a p...",1,1971,0.4702,PT
2,"Foreign direct investment, net inflows, as a p...",1,1972,0.42351,PT
3,"Foreign direct investment, net inflows, as a p...",1,1973,0.47988,PT
4,"Foreign direct investment, net inflows, as a p...",1,1974,0.49684,PT

In [65]:
nacoesunidas_2['INDICADOR'].unique()

array(['Foreign direct investment, net inflows, as a proportion of GDP (%) [17.13.1]',
       'Renewable energy share in the total final energy consumption [7.2.1]',
       'Annual inflation, consumer prices (%) [17.13.1]',
       'Proportion of individuals who own a mobile telephone [5.b.1]',
       'Annual GDP growth (%) [17.13.1]',
       'Annual growth rate of real GDP per capita [8.1.1]',
       'SE_ACS_ELECT',
       'Proportion of youth and adults with information and communications technology (ICT) skills [4.4.1]',
       'Participation rate in formal and non-formal education and training [4.3.1]',
       'Gender parity index for youth/adults with information and communications technology (ICT) skills [4.5.1]',
       'Adjusted gender parity index for participation rate in formal and non-formal education and training (ratio) [4.5.1]',
       'Proportion of elected seats held by women in deliberative bodies of local government [5.5.1]',
       'Proportion of seats held by women in national parliaments (% of total number of seats) [5.5.1]',
       'Number of seats held by women in national parliaments [5.5.1]',
       'Current number of seats in national parliaments [5.5.1]',
       'Alcohol consumption per capita (aged 15 years and older) within a calendar year [3.5.2]',
       'Mortality rate attributed to cardiovascular disease, cancer, diabetes or chronic respiratory disease [3.4.1]',
       'Infant mortality rate [3.2.1]', 'SH_DYN_IMRTN', 'SH_FPL_MTMM',
       'Health worker density, by type of occupation (per 10,000 population) [3.c.1]',
       'Health worker distribution, by sex and type of occupation [3.c.1]',
       'Proportion of births attended by skilled health personnel [3.1.2]',
       'Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene from diarrhoea, intestinal nematode infections, malnutrition and acute respiratory infections [3.9.2]',
       'Proportion of unemployed persons receiving unemployment cash benefit [1.3.1]',
       'Proportion of vulnerable population receiving social assistance cash benefit [1.3.1]',
       'Proportion of population living below the national poverty line [1.2.1]',
       'Average hourly earnings [8.5.1]',
       'Annual growth rate of real GDP per employed person [8.2.1]',
       'Unemployment rate, by sex and age - 13th ICLS (%) [8.5.2]',
       'Prevalence of undernourishment [2.1.1]',
       'Proportion of population using basic drinking water services [1.4.1]',
       'Proportion of population using basic sanitation services [1.4.1]',
       'Merchandise trade as a proportion of GDP (%) [17.13.1]'],
      dtype=object)

In [67]:
nacoesunidas_2['INDICADOR'] = nacoesunidas_2['INDICADOR'].str.replace(r'\[.*\]', '', regex=True).str.strip()
nacoesunidas_2['INDICADOR'].unique()

array(['Foreign direct investment, net inflows, as a proportion of GDP (%)',
       'Renewable energy share in the total final energy consumption',
       'Annual inflation, consumer prices (%)',
       'Proportion of individuals who own a mobile telephone',
       'Annual GDP growth (%)',
       'Annual growth rate of real GDP per capita', 'SE_ACS_ELECT',
       'Proportion of youth and adults with information and communications technology (ICT) skills',
       'Participation rate in formal and non-formal education and training',
       'Gender parity index for youth/adults with information and communications technology (ICT) skills',
       'Adjusted gender parity index for participation rate in formal and non-formal education and training (ratio)',
       'Proportion of elected seats held by women in deliberative bodies of local government',
       'Proportion of seats held by women in national parliaments (% of total number of seats)',
       'Number of seats held by women in national parliaments',
       'Current number of seats in national parliaments',
       'Alcohol consumption per capita (aged 15 years and older) within a calendar year',
       'Mortality rate attributed to cardiovascular disease, cancer, diabetes or chronic respiratory disease',
       'Infant mortality rate', 'SH_DYN_IMRTN', 'SH_FPL_MTMM',
       'Health worker density, by type of occupation (per 10,000 population)',
       'Health worker distribution, by sex and type of occupation',
       'Proportion of births attended by skilled health personnel',
       'Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene from diarrhoea, intestinal nematode infections, malnutrition and acute respiratory infections',
       'Proportion of unemployed persons receiving unemployment cash benefit',
       'Proportion of vulnerable population receiving social assistance cash benefit',
       'Proportion of population living below the national poverty line',
       'Average hourly earnings',
       'Annual growth rate of real GDP per employed person',
       'Unemployment rate, by sex and age - 13th ICLS (%)',
       'Prevalence of undernourishment',
       'Proportion of population using basic drinking water services',
       'Proportion of population using basic sanitation services',
       'Merchandise trade as a proportion of GDP (%)'], dtype=object)

In [91]:
pais_prov = pd.read_csv(r'C:\Users\carlo\OneDrive\ANALYTICS\ANALYTICS - IRONHACK\PORTFOLIO\PROJETOS\PROJETO_FINAL_CURSO\Nacoes_Unidas\Dados_Nacoes_Unidas\paises_segundo_df.csv')

In [100]:
pattern = r'\[(\d+)\]\s-\s([a-zA-Z\s]+)'  # Regex para extrair [cÃ³digo] e nome do paÃ­s para substituir no dataframe
matches = re.findall(pattern, str(pais_prov))  # Encontra todos os padrÃµes no texto
results = [(match[0]+ ':' + match[1]) for match in matches]  # Cria uma lista de tuplas com os valores correspondentes aos padrÃµes encontrados

nome_pais = []  # Cria uma lista vazia chamada 'flores'

for result in results:
    nome_pais.append(result)  # Adiciona cada tupla de resultado Ã  lista 'flores'

print(nome_pais)  # Exibe a lista 'flores' com os resultados

['1:World', '1:World', '1:World', '100:Bulgaria', '100:Bulgaria', '104:Myanmar', '104:Myanmar', '108:Burundi', '108:Burundi', '11:Western Africa', '11:Western Africa', '112:Belarus', '112:Belarus', '116:Cambodia', '116:Cambodia', '12:Algeria', '12:Algeria', '120:Cameroon', '120:Cameroon', '124:Canada', '124:Canada', '13:Central America', '13:Central America', '132:Cabo Verde', '132:Cabo Verde', '136:Cayman Islands', '136:Cayman Islands', '14:Eastern Africa', '14:Eastern Africa', '140:Central African Republic', '140:Central African Republic', '142:Asia', '142:Asia', '143:Central Asia', '143:Central Asia', '144:Sri Lanka', '144:Sri Lanka', '145:Western Asia', '145:Western Asia', '148:Chad', '148:Chad', '15:Northern Africa', '15:Northern Africa', '150:Europe', '150:Europe', '151:Eastern Europe', '151:Eastern Europe', '152:Chile', '152:Chile', '154:Northern Europe', '154:Northern Europe', '155:Western Europe', '155:Western Europe', '156:China', '156:China', '17:Middle Africa', '17:Middle Africa', '170:Colombia', '170:Colombia', '174:Comoros', '174:Comoros', '178:Congo', '178:Congo', '18:Southern Africa', '18:Southern Africa', '180:Democratic Republic of the Congo', '180:Democratic Republic of the Congo', '188:Costa Rica', '188:Costa Rica', '19:Americas', '19:Americas', '191:Croatia', '191:Croatia', '196:Cyprus', '196:Cyprus', '199:Least Developed Countries ', '199:Least Developed Countries ', '2:Africa', '2:Africa', '202:Sub', '202:Sub', '203:Czechia', '203:Czechia', '204:Benin', '204:Benin', '208:Denmark', '208:Denmark', '21:Northern America', '21:Northern America', '212:Dominica', '212:Dominica', '214:Dominican Republic', '214:Dominican Republic', '218:Ecuador', '218:Ecuador', '222:El Salvador', '222:El Salvador', '226:Equatorial Guinea', '226:Equatorial Guinea', '231:Ethiopia', '231:Ethiopia', '232:Eritrea', '232:Eritrea', '233:Estonia', '233:Estonia', '24:Angola', '24:Angola', '242:Fiji', '242:Fiji', '246:Finland', '246:Finland', '250:France', '250:France', '258:French Polynesia', '258:French Polynesia', '262:Djibouti', '262:Djibouti', '266:Gabon', '266:Gabon', '268:Georgia', '268:Georgia', '270:Gambia', '270:Gambia', '275:State of Palestine', '275:State of Palestine', '276:Germany', '276:Germany', '28:Antigua and Barbuda', '28:Antigua and Barbuda', '288:Ghana', '288:Ghana', '296:Kiribati', '296:Kiribati', '30:Eastern Asia', '30:Eastern Asia', '300:Greece', '300:Greece', '308:Grenada', '308:Grenada', '31:Azerbaijan', '31:Azerbaijan', '32:Argentina', '32:Argentina', '320:Guatemala', '320:Guatemala', '324:Guinea', '324:Guinea', '328:Guyana', '328:Guyana', '332:Haiti', '332:Haiti', '34:Southern Asia', '34:Southern Asia', '340:Honduras', '340:Honduras', '344:China', '344:China', '348:Hungary', '348:Hungary', '35:South', '35:South', '352:Iceland', '352:Iceland', '356:India', '356:India', '36:Australia', '36:Australia', '360:Indonesia', '360:Indonesia', '364:Iran ', '364:Iran ', '368:Iraq', '368:Iraq', '372:Ireland', '372:Ireland', '376:Israel', '376:Israel', '380:Italy', '380:Italy', '384:C', '384:C', '388:Jamaica', '388:Jamaica', '39:Southern Europe', '39:Southern Europe', '392:Japan', '392:Japan', '398:Kazakhstan', '398:Kazakhstan', '4:Afghanistan', '4:Afghanistan', '40:Austria', '40:Austria', '400:Jordan', '400:Jordan', '404:Kenya', '404:Kenya', '410:Republic of Korea', '410:Republic of Korea', '412:Kosovo', '412:Kosovo', '414:Kuwait', '414:Kuwait', '417:Kyrgyzstan', '417:Kyrgyzstan', '418:Lao People', '418:Lao People', '419:Latin America and the Caribbean', '419:Latin America and the Caribbean', '422:Lebanon', '422:Lebanon', '426:Lesotho', '426:Lesotho', '428:Latvia', '428:Latvia', '430:Liberia', '430:Liberia', '432:Landlocked developing countries ', '432:Landlocked developing countries ', '434:Libya', '434:Libya', '438:Liechtenstein', '438:Liechtenstein', '44:Bahamas', '44:Bahamas', '440:Lithuania', '440:Lithuania', '442:Luxembourg', '442:Luxembourg', '446:China', '446:China', '450:Madagascar', '450:Madagascar', '454:Malawi', '454:Malawi', '458:Malaysia', '458:Malaysia', '462:Maldives', '462:Maldives', '466:Mali', '466:Mali', '470:Malta', '470:Malta', '478:Mauritania', '478:Mauritania', '48:Bahrain', '48:Bahrain', '480:Mauritius', '480:Mauritius', '484:Mexico', '484:Mexico', '496:Mongolia', '496:Mongolia', '498:Republic of Moldova', '498:Republic of Moldova', '499:Montenegro', '499:Montenegro', '5:South America', '5:South America', '50:Bangladesh', '50:Bangladesh', '504:Morocco', '504:Morocco', '508:Mozambique', '508:Mozambique', '51:Armenia', '51:Armenia', '512:Oman', '512:Oman', '513:Europe and Northern America', '513:Europe and Northern America', '516:Namibia', '516:Namibia', '52:Barbados', '52:Barbados', '524:Nepal', '524:Nepal', '528:Netherlands ', '528:Netherlands ', '53:Australia and New Zealand', '53:Australia and New Zealand', '531:Cura', '531:Cura', '533:Aruba', '533:Aruba', '534:Sint Maarten ', '534:Sint Maarten ', '54:Melanesia', '54:Melanesia', '540:New Caledonia', '540:New Caledonia', '543:Oceania ', '543:Oceania ', '548:Vanuatu', '548:Vanuatu', '554:New Zealand', '554:New Zealand', '558:Nicaragua', '558:Nicaragua', '56:Belgium', '56:Belgium', '562:Niger', '562:Niger', '566:Nigeria', '566:Nigeria', '57:Micronesia', '57:Micronesia', '578:Norway', '578:Norway', '583:Micronesia ', '583:Micronesia ', '584:Marshall Islands', '584:Marshall Islands', '585:Palau', '585:Palau', '586:Pakistan', '586:Pakistan', '591:Panama', '591:Panama', '598:Papua New Guinea', '598:Papua New Guinea', '60:Bermuda', '60:Bermuda', '600:Paraguay', '600:Paraguay', '604:Peru', '604:Peru', '608:Philippines', '608:Philippines', '61:Polynesia', '61:Polynesia', '616:Poland', '616:Poland', '62:Central and Southern Asia', '62:Central and Southern Asia', '620:Portugal', '620:Portugal', '624:Guinea', '624:Guinea', '626:Timor', '626:Timor', '634:Qatar', '634:Qatar', '64:Bhutan', '64:Bhutan', '642:Romania', '642:Romania', '643:Russian Federation', '643:Russian Federation', '646:Rwanda', '646:Rwanda', '659:Saint Kitts and Nevis', '659:Saint Kitts and Nevis', '662:Saint Lucia', '662:Saint Lucia', '670:Saint Vincent and the Grenadines', '670:Saint Vincent and the Grenadines', '678:Sao Tome and Principe', '678:Sao Tome and Principe', '68:Bolivia ', '68:Bolivia ', '682:Saudi Arabia', '682:Saudi Arabia', '686:Senegal', '686:Senegal', '688:Serbia', '688:Serbia', '690:Seychelles', '690:Seychelles', '694:Sierra Leone', '694:Sierra Leone', '70:Bosnia and Herzegovina', '70:Bosnia and Herzegovina', '702:Singapore', '702:Singapore', '703:Slovakia', '703:Slovakia', '704:Viet Nam', '704:Viet Nam', '705:Slovenia', '705:Slovenia', '706:Somalia', '706:Somalia', '710:South Africa', '710:South Africa', '716:Zimbabwe', '716:Zimbabwe', '72:Botswana', '72:Botswana', '722:Small island developing States ', '722:Small island developing States ', '724:Spain', '724:Spain', '728:South Sudan', '728:South Sudan', '729:Sudan', '729:Sudan', '740:Suriname', '740:Suriname', '747:Northern Africa and Western Asia', '747:Northern Africa and Western Asia', '748:Eswatini', '748:Eswatini', '752:Sweden', '752:Sweden', '753:Eastern and South', '753:Eastern and South', '756:Switzerland', '756:Switzerland', '76:Brazil', '76:Brazil', '760:Syrian Arab Republic', '760:Syrian Arab Republic', '762:Tajikistan', '762:Tajikistan', '764:Thailand', '764:Thailand', '768:Togo', '768:Togo', '776:Tonga', '776:Tonga', '780:Trinidad and Tobago', '780:Trinidad and Tobago', '784:United Arab Emirates', '784:United Arab Emirates', '788:Tunisia', '788:Tunisia', '792:T', '792:T', '795:Turkmenistan', '795:Turkmenistan', '796:Turks and Caicos Islands', '796:Turks and Caicos Islands', '798:Tuvalu', '798:Tuvalu', '8:Albania', '8:Albania', '800:Uganda', '800:Uganda', '804:Ukraine', '804:Ukraine', '807:North Macedonia', '807:North Macedonia', '818:Egypt', '818:Egypt', '826:United Kingdom of Great Britain and Northern Ireland', '826:United Kingdom of Great Britain and Northern Ireland', '834:United Republic of Tanzania', '834:United Republic of Tanzania', '84:Belize', '84:Belize', '840:United States of America', '840:United States of America', '854:Burkina Faso', '854:Burkina Faso', '858:Uruguay', '858:Uruguay', '860:Uzbekistan', '860:Uzbekistan', '862:Venezuela ', '862:Venezuela ', '882:Samoa', '882:Samoa', '887:Yemen', '887:Yemen', '894:Zambia', '894:Zambia', '9:Oceania', '9:Oceania', '90:Solomon Islands', '90:Solomon Islands', '96:Brunei Darussalam', '96:Brunei Darussalam']

In [ ]:
# Substituir os valores da coluna 'PAIS' pelos nomes dos paÃ­ses

In [ ]:
nacoesunidas_2['SERIES', 'REF_AREA', 'SEX',
       'AGE', 'URBANISATION', 'EDUCATION_LEV',
       'OCCUPATION', 'CUST_BREAKDOWN', 'COMPOSITE_BREAKDOWN',
       'DISABILITY_STATUS', 'ACTIVITY', 'PRODUCT', 'TIME_PERIOD', 'OBS_VALUE',
       'OBS_STATUS', 'UNIT_MULT', 'UNIT_MEASURE', 'BASE_PER', 'NATURE',
       'TIME_DETAIL', 'COMMENT_OBS', 'TIME_COVERAGE', 'UPPER_BOUND',
       'LOWER_BOUND', 'SOURCE_DETAIL', 'COMMENT_TS', 'GEO_INFO_URL',
       'GEO_INFO_TYPE', 'CUST_BREAKDOWN_LB', 'DATA_LAST_UPDATE']

In [ ]:
'SI_POV_NAHC':'Proportion of population living below the national poverty line [1.2.1]'
'SI_COV_UEMP':'Proportion of unemployed persons receiving unemployment cash benefit [1.3.1]'
'SI_COV_VULN':'Proportion of vulnerable population receiving social assistance cash benefit [1.3.1]'
'SP_ACS_BSRVSAN':'Proportion of population using basic sanitation services [1.4.1]'
'SP_ACS_BSRVH2O':'Proportion of population using basic drinking water services [1.4.1]'
'SN_ITK_DEFC':'Prevalence of undernourishment [2.1.1]'
'SN_ITK_DEFCN':'Number of undernourish people [2.1.1]'
'SH_STA_BRTC':'Proportion of births attended by skilled health personnel [3.1.2]'
'SH_DYN_IMRT':'Infant mortality rate [3.2.1]'
'SH_DTH_NCOM':'Mortality rate attributed to cardiovascular disease, cancer, diabetes or chronic respiratory disease [3.4.1]'
'SH_ALC_CONSPT':'Alcohol consumption per capita (aged 15 years and older) within a calendar year [3.5.2]'
'SH_STA_WASHARI':'Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene from diarrhoea, intestinal nematode infections, malnutrition and acute respiratory infections [3.9.2]'
'SH_MED_DEN':'Health worker density, by type of occupation (per 10,000 population) [3.c.1]'
'SH_MED_HWRKDIS':'Health worker distribution, by sex and type of occupation [3.c.1]'
'SE_ADT_EDUCTRN':'Participation rate in formal and non-formal education and training [4.3.1]'
'SE_ADT_ACTS':'Proportion of youth and adults with information and communications technology (ICT) skills [4.4.1]'
'SE_GPI_PART':'Adjusted gender parity index for participation rate in formal and non-formal education and training (ratio) [4.5.1]'
'SE_GPI_ICTS':'Gender parity index for youth/adults with information and communications technology (ICT) skills [4.5.1]'
'VC_VAW_MARR':'Proportion of ever-partnered women and girls subjected to physical and sexual violence by a current or former intimate partner in the previous 12 months [5.2.1]'
'SG_GEN_LOCGELS':'Proportion of elected seats held by women in deliberative bodies of local government [5.5.1]'
'SG_GEN_PARL':'Proportion of seats held by women in national parliaments (% of total number of seats) [5.5.1]'
'SG_GEN_PARLN':'Number of seats held by women in national parliaments [5.5.1]'
'SG_GEN_PARLNT':'Current number of seats in national parliaments [5.5.1]'
'IT_MOB_OWN':'Proportion of individuals who own a mobile telephone [5.b.1]'
'EG_ACS_ELEC':'Proportion of population with access to electricity [7.1.1]'
'EG_FEC_RNEW':'Renewable energy share in the total final energy consumption [7.2.1]'
'NY_GDP_PCAP':'Annual growth rate of real GDP per capita [8.1.1]'
'SL_EMP_PCAP':'Annual growth rate of real GDP per employed person [8.2.1]'
'SL_EMP_EARN':'Average hourly earnings [8.5.1]'
'SL_TLF_UEM':'Unemployment rate, by sex and age - 13th ICLS (%) [8.5.2]'
'BX_KLT_DINV_WD_GD_ZS':'Foreign direct investment, net inflows, as a proportion of GDP (%) [17.13.1]'
'NY_GDP_MKTP_KD_ZG':'Annual GDP growth (%) [17.13.1]'
'FP_CPI_TOTL_ZG':'Annual inflation, consumer prices (%) [17.13.1]'
'TG_VAL_TOTL_GD_ZS':'Merchandise trade as a proportion of GDP (%) [17.13.1]'